CHANGELOG.md
README.md
TODO.md
examples/drupal_loadtest.rs
examples/simple.rs
src/goose.rs
src/lib.rs
src/manager.rs
src/stats.rs
src/worker.rs

For Michael, a Goose load test is now officially called a GooseAttack.

convert GooseState to GooseAttack

---

CHANGELOG.md
Cargo.toml
src/manager.rs

Replace `unsafe` blocks with `lazy_static` singleton

remove unsafe blocks

---

CHANGELOG.md
Cargo.toml
README.md

push new release to update documentation

release 0.6.2

---

.github/workflows/CI.yml
examples/drupal_loadtest.rs
examples/simple.rs
src/client.rs
src/goose.rs
src/lib.rs
src/manager.rs
src/stats.rs
src/util.rs
src/worker.rs

Cleanup code formatting with `cargo fmt`

run `cargo fmt`

---

src/client.rs
src/goose.rs
src/lib.rs
src/stats.rs
src/util.rs

Clippy cleanup

---

src/lib.rs
src/manager.rs
src/worker.rs

fix #33 optimize nng usage

---

CHANGELOG.md
README.md
examples/drupal_loadtest.rs
examples/simple.rs
src/goose.rs
src/lib.rs
src/prelude.rs

- add new goose::prelude
- update all documentation and examples

fix #29 add goose::prelude

---

src/lib.rs

- fix panic when calling `test_start` or `test_stop` to setup/teardown test

propery initialize temp client for setup/teardown

---

tests/gaggle.rs

Requires #57 to pass.
Runs a distributed Gaggle load test.

add test for distributed gaggle

---

src/goose.rs

Absolute paths always work, so using them consistently.

use absolute paths

---

src/goose.rs

more link fixes

---

.github/workflows/CI.yml
examples/drupal_loadtest.rs
src/goose.rs
src/lib.rs
src/logger.rs
src/manager.rs
src/worker.rs
tests/logs.rs
tests/no_normal_tasks.rs
tests/one_taskset.rs
tests/redirect.rs

Fix all code-style issues reported by clippy

code cleanup with clippy

---

Cargo.toml
README.md

From #85
- rebased against master
- reworked README a little

expose feature to optionally compile with rustls

---

src/goose.rs
src/lib.rs

something that tripped me up at first

fix docs, requests need to be awaited

---

src/lib.rs

Split off non-throttle-related cleanup from #97 into its own PR

setup logger thread in function

---

README.md

Update the README with the new `.print()` function and `fmt::Display()` changes.

update README with new stats details

---

CHANGELOG.md
src/goose.rs
src/lib.rs

Display an actual/useful error.
Fix #127

properly display errors

---

CHANGELOG.md
Cargo.toml
README.md
src/goose.rs
src/lib.rs
src/manager.rs
src/metrics.rs
src/util.rs
tests/redirect.rs

All currently planned API-affecting changes are done, tagging `0.10` for release.

Release 0.10

---

CHANGELOG.md
Cargo.toml
README.md

release v0.10.2

---

examples/umami/common.rs

- move logic to get a random language-appropriate word from titles (originally used for search) into a function
- search for multiple random words instead of just 1 word
- randomly generate name, email, subject and message for content form using the same logic
- remove `info!()` when contact form is throttled as this happens too often for the information to be helpful when running a load test

get language-appropriate random words from titles

---

Dockerfile

Add docker file to create manager and worker images for for use in testing new drupal profile
Note: not ready for merge

Add initial OCI Dockerfile

---

CHANGELOG.md
README.md

Add Quay icon + Changelog entry

---

Dockerfile
docker-entrypoint.sh

Rewrite Dockerfiles to use on image and make it generic. Allow for options to be passed on the command line.

Make Dockerfile generic

---

CHANGELOG.md
Cargo.toml
README.md

release 0.10.4

---

CHANGELOG.md
src/lib.rs
src/logger.rs
src/metrics.rs
src/prelude.rs

- add missing documentation for all high level public files and functions
- fixes #135

document high level public files and functions

---

src/lib.rs

Fix a clippy-identified errors
- several functions were returning Result<> without ever returning an Err
- fixes test errors

remove unnessary Results

---

Cargo.toml
src/goose.rs
tests/closure.rs
tests/common.rs
tests/defaults.rs
tests/logs.rs
tests/no_normal_tasks.rs
tests/one_taskset.rs
tests/redirect.rs
tests/scheduler.rs
tests/sequence.rs
tests/setup_teardown.rs
tests/throttle.rs

This PR will update httpmock to the most recent version. Deprecated parts have been rewritten to align with the new version.

Updated httpmock to the most recent version

---

CHANGELOG.md
examples/umami/common.rs

- simplify regex per clippy suggestion

simplify umami form matching regex

---

src/goose.rs
src/lib.rs
src/logger.rs
src/metrics.rs

- consistently link to appropriate documentation where possible
- make all documentation tests run
- document all functions

make documentation more consistent

---

CHANGELOG.md
Cargo.toml
src/controller.rs
src/metrics.rs
tests/common.rs
tests/controller.rs

- test coverage for telnet Controller
- test coverage for WebSocket Controller
- no Gaggle tests as Controllers are currently disabled when running in Gaggle distributed load test mode

automated testing for telnet and WebSocket Controllers

---

README.md
src/lib.rs

Close issue #308.
Signed-off-by: Begley Brothers Inc <begleybrothers@gmail.com>

[Evolve][Misc] White space cleanup

---

CHANGELOG.md
src/goose.rs

- document how to add custom cookies (will show up at https://docs.rs/goose/*/goose/goose/struct.GooseUser.html#custom-cookies once this is released)
- fixes #231

document how to add a custom cookie

---

CHANGELOG.md
Cargo.toml

Update the [`rustc_version`](https://docs.rs/rustc_version/) dependency

update rustc_version dependency to latest version

---

CHANGELOG.md
Cargo.toml
tests/closure.rs
tests/controller.rs
tests/defaults.rs
tests/error.rs
tests/logs.rs
tests/no_normal_tasks.rs
tests/one_taskset.rs
tests/redirect.rs
tests/scheduler.rs
tests/sequence.rs
tests/setup_teardown.rs
tests/throttle.rs

- updated [`httpmock`](https://docs.rs/httpmock) dev dependency to [`0.6`](https://github.com/alexliesenfeld/httpmock/blob/master/CHANGELOG.md)

update httpmock dependency

---

CHANGELOG.md
Cargo.toml
README.md

Open 0.14.1-dev for development.

open 0.14.1-dev

---

CHANGELOG.md

This sneaked out of the original pull request.

#246: Add requests per second graph in HTML report to the changelog.

---

src/docs/goose-book/src/getting-started/common.md

Another small documentation update ;)

fix startup-time documentation

---

Cargo.toml
examples/closure.rs
examples/drupal_memcache.rs
examples/session.rs
examples/simple.rs
src/logger.rs
src/metrics.rs

- fix formatting and clippy warnings

fix formatting and clippy warnings

---

CHANGELOG.md
src/config.rs
src/metrics.rs

#430: Rename --no-granular-data to --no-granular-report.

---

src/metrics.rs

Test plan steps overview should display times in the local timezone

---

.github/workflows/CI.yml

Closes #447.
Based on https://stackoverflow.com/questions/64634535/github-actions-cache-rust-artifacts.

#447: Cache build artifacts across CI builds.

---

src/docs/goose-book/src/config/defaults.md

You can fetch upstream in the GH GUI now. I think these are the only changes that needed to be made after upstream fetch. Not sure about line 97 onward. I'm using Linux are you on Windows (or someone on your team?).
- Closes https://github.com/tag1consulting/goose/pull/463

small doc updates

---

CHANGELOG.md
Cargo.toml
src/docs/goose-book/src/getting-started/creating.md
src/docs/goose-book/src/getting-started/metrics.md

release 0.16.2

---

src/controller.rs
src/goose.rs
src/lib.rs
tests/closure.rs
tests/one_taskset.rs

fix issues from latest clippy update

clippy fixes

---

CHANGELOG.md
src/config.rs

Impl `Default` for `GooseConfiguration`

---

CHANGELOG.md
Cargo.toml
src/docs/goose-book/src/controller/telnet.md
src/docs/goose-book/src/getting-started/creating.md
src/docs/goose-book/src/getting-started/metrics.md
src/docs/goose-book/src/getting-started/scenarios.md

release 0.16.4

---

src/metrics.rs

Fixed copy paste error in docs

fix GooseRequestMetric::redirect docs

---

src/logger.rs
src/metrics.rs
tests/redirect.rs

- removes a debug message that wasn't supposed to be committed
- fix some new clippy warnings
- closes #534

remove debug message

---

CHANGELOG.md
Cargo.toml
src/docs/goose-book/src/controller/telnet.md
src/docs/goose-book/src/getting-started/creating.md
src/docs/goose-book/src/getting-started/metrics.md
src/docs/goose-book/src/getting-started/scenarios.md

Release 0.17.1.
Update documentation.

tag 0.17.1 release

---

memory-bank/activeContext.md
memory-bank/productContext.md
memory-bank/progress.md
memory-bank/projectbrief.md
memory-bank/systemPatterns.md
memory-bank/techContext.md

- started with a qwen2.5-coder local module to create initial memory-bank files
- used Claude 3.7 Sonnet to improve documentation
- fleshed out gaggle roadmap
More information about Cline can be found at https://cline.bot/
These changes don't make any functional changes to the project, they help to define the project for use with AI-assisted development and review. Any review of these changes should validate accuracy and completeness of the memory-bank.

Integrate Cline memory-bank, providing additional documentation

---

src/lib.rs
src/test_plan.rs
tests/common.rs
tests/test_plan.rs

Closes https://github.com/tag1consulting/goose/issues/626
__Target Functionality__: Test plan parsing and validation - a critical user-facing feature that converts string-formatted test plans (like `"10,30s;20,1m;0,10s"`) into Goose's internal representation.
__Test Coverage Added__: 11 comprehensive test functions covering:
- __Valid test plan parsing__ - Tests various time formats (seconds, minutes, hours, combinations)
- __Whitespace handling__ - Ensures robust parsing with extra spaces and different whitespace
- __Zero values__ - Edge cases with zero users or zero time
- __Large numbers__ - Stress testing with large user counts and time values
- __Invalid formats__ - Comprehensive testing of malformed input with proper error validation
- __Edge cases__ - Missing commas, invalid …

add test-plan tests

---

memory-bank/activeContext.md
memory-bank/progress.md
src/controller.rs
src/goose.rs
src/lib.rs
src/logger.rs
src/metrics.rs
src/throttle.rs
src/user.rs

Replaces https://github.com/tag1consulting/goose/pull/617
Standardize the log message formatting, ie "[user {}]:".
Document the change. This change enhances the maintainability of the codebase by standardizing the log format.

Logging consistency

---

src/config.rs
src/metrics.rs
src/metrics/nullable.rs

The baseline comparison feature for Goose load testing framework was implemented using a sequential three-branch strategy to break down a large feature (~2,100 lines across 18 files) into manageable, focused pull requests.
The `baseline-infrastructure` branch has been completed and provides:
- CLI integration for `--baseline-file` option
- Configuration structure ready for baseline file paths
- Foundation for subsequent processing and reporting logic
- Clean compilation without warnings or errors
The infrastructure is now ready for the processing logic implementation in the next PR.
These three PRs together replace https://github.com/tag1consulting/goose/pull/653 and https://github.com/tag1consulting/goose/pull/602
**Base**: `main`
**Purpose**: Foundation layer for baseline comparison …

Baseline infrastructure (Baseline 1 of 3)
