tag1consulting/goose

TODO.md, src/goose.rs, src/lib.rs, src/stats.rs, src/util.rs
- remove response_times from unordered HashMap to an ordered BTreeMap
- round response_times to compress the data
- maintain running min/max/total counters to minimize CPU overhead
- rework median() to use grouped BTreeMap response time counters
- rework calculation of percentiles to use grouped BTreeMap response time counters
=> optimize statistics

TODO.md, src/client.rs
Fixes #3 
- wake clients regularly to poll for messages from the parent
- exit quickly if parent sends GooseClientCommand::EXIT
- send updated statistics quickly if parent sens GooseClientCommand::SYNC
=> poll regularly to exit to fix #3 

src/goose.rs
Don't start rounding response times until we get to 100 ms, capturing more response time detail.
=> capture more response time detail

CHANGELOG.md, README.md, src/goose.rs, src/lib.rs, src/manager.rs
replace `--print-stats` with `--no-stats`, as structopt defaults boolean options to false
=> default to printing stats

CHANGELOG.md, Cargo.toml, README.md, src/lib.rs
Status: This is mostly working. Which is to say, it properly makes Gaggle's a compile-time only option. The problem is, this means we can no longer use the examples to run a gaggle.
Offhand, it seems this isn't possible, ie https://github.com/rust-lang/cargo/issues/2911
=> [WIP] wrap gaggle code in compile-time feature

CHANGELOG.md, README.md, TODO.md, src/goose.rs, src/lib.rs, src/manager.rs, src/worker.rs
- hash the load test
- workers push hash to manager to validate
- exit if hashes don't match
- introduce `--no-hash-check` flag to optionally ignored mismatched load tests
=> verify manager and workers are running same load test

src/goose.rs, src/lib.rs, src/manager.rs, src/stats.rs, src/worker.rs
consistently refer to `GooseAttack` as `goose_attack`, removing old references to `goose_state`.
=> Consistency

CHANGELOG.md, README.md, TODO.md, examples/drupal_loadtest.rs, examples/simple.rs, src/goose.rs, src/lib.rs
Simplify declaration of load tests, remove need for adding `use std::boxed::Box`.
=> fix #30, use full path to std::boxed::Box

src/lib.rs
Currently goose shuffles task sets after it weights them. 
For example, if a test plan defines Task Set A with a weight of 3, and Task Set B with a weight of 1, when the test runs it builds a weighted list: "AAAB", it then shuffles this list for example, "AABA". Now, say we spin up 6 clients it'll launch "AAABAA". 
Now, if it runs again, the shuffle may order the weighted list "ABAA" and when we spin up 6 clients it'll instead launch "ABAAAB".  Thus when we run the same load test two times in a row we end up generating different load (5 A's and 1 B the first time, 4 A's and 2 B's the second time).
This PR removes the shuffle of weighted task sets, so two tests with the same # of clients will always launch the same clients. Clients are launched in the order they're defined. (So after this …
=> don't shuffle weighted task sets

CHANGELOG.md, Cargo.toml, examples/drupal_loadtest.rs, src/client.rs, src/goose.rs, src/lib.rs, src/manager.rs, src/prelude.rs, src/stats.rs
In the current implementation, each Goose client thread processes requests and maintains statistics, which are pushed up to the client every 15 seconds. 
The intent of this PR is to instead push the raw requests/response details to the parent immediately, offloading the overhead of calculating statistics so clients can run as quickly as possible. This will primarily benefit a Goose Attack if the load test server isn't already using 100% of the CPU.
**Crossbeam**
- With a non-starved CPU we're seeing a ~2% performance improvement
- With a starved CPU we're seeing a ~2-3% performance improvement
**Tokio mpsc**
- With a non-starved CPU we're seeing a ~2.1% performance improvement
- With a starved CPU we're seeing a ~1-2% performance improvement
The raw numbers:
- …
=> push per-thread statistics to parent immediately

CHANGELOG.md, examples/drupal_loadtest.rs, src/goose.rs
Requests made by Goose return a custom GooseResponse object which currently contains but the request made, and the response.
Subsequent calls to `set_success` and `set_failure` must include a mutable reference to the request that was made. For example:
```rust
use goose::prelude::*;
let mut task = task!(get_function);
/// A simple task that makes a GET request.
async fn get_function(client: &mut GooseClient) {
let mut response = client.get("/404").await;
match &response.response {
Ok(r) => {
// We expect a 404 here.
if r.status() == 404 {
client.set_success(&mut response.request);
}
},
Err(_) => (),
}
}
````
=> reimplement set_success and set_failure, fix #40

CHANGELOG.md, Cargo.toml, examples/drupal_loadtest.rs, examples/simple.rs, src/client.rs, src/goose.rs, src/lib.rs, src/worker.rs
Make GooseClient immutable, and generally cleanup the API for consistency (storing things like the request name in a mutable GooseClient had unintended consequences: for example, we weren't loading static assets but the previous implementation hid this as we'd end up naming the wrong request)
Mutable parts are moved into a global Vector of mutable GooseClientState objects (one per client thread), all wrapped in a RwLock().
The Vector is written to only once at startup, after which we're always just grabbing the lock with a `.read()` minimize the performance impact.
Inside `GooseClientState` are currently three mutable values:
```
struct GooseClientState {
/// A Reqwest client, wrapped in a Mutex as a read-write copy is always needed to
/// manage things like sessions and cookies.
client: …
```
=> make GooseClient immutable

CHANGELOG.md, src/lib.rs
Required for a client load test, adds ability to define an optional `test_start_task` and/or an optional `test_stop_task`. These tasks are only run one time. If running in a Gaggle, the tasks are run by the Manager process.
```rust
use goose::prelude::*;
fn main() {
GooseAttack::initialize()
.test_start(task!(setup))
.register_taskset(taskset!("FooTasks")
.register_task(task!(foo_task))
)
.test_stop(task!(teardown))
.execute();
}
async fn setup(client: &GooseClient) {
// do stuff to set up the load test ...
}
async fn teardown(client: &GooseClient) {
// do stuff to tear down the load test ...
}
async fn foo_task(client: &GooseClient) {
// this is a normal load test task ...
client.get("/foo");
}
```
=> fix #45 run optional test_start_task and test_stop_task

CHANGELOG.md, src/client.rs
- allow a load-test to be just `on_start` and/or `on_exit` tasks
=> fix #44 dont panic if there are no normal tasks

src/goose.rs, src/lib.rs, src/util.rs
- [bugfix] send_to_parent can only send messages if there is a parent
- [bugfix] always store status_code in raw-request
- [cleanup] a task set can have on_start or on_exit tasks, so don't exist if the task list is empty, the client can handle
- [cleanup] reduce severity of non-critical issues
- [bugfix] don't exit if we fail to setup logger (this can happen in testing environments)
=> cleanup and bug fixing

CHANGELOG.md, src/lib.rs, src/worker.rs
- always initialize global state (otherwise gaggles panic)
- don't exit worker process if manager process goes away during shutdown
These fixes are required for #56
=> properly initialize global state so gaggles work

src/manager.rs, src/worker.rs
Instead of writing to a buffer and then converting to a Message, write directly to the Message. Based on feedback in #33.
This PR includes #57 as I needed Gaggles working to test it. I'll rebase once #57 lands.
=> optimize NNG usage

tests/setup_teardown.rs
- requires #54 to pass
- test 1: run `test_start` to perform load-test setup
- test 2: run `test_stop` to perform load-test cleanup
- test 3: run `test_start` and `test_stop`, launch multiple clients, confirm both run correctly one time only
=> tests for test_start and test_stop

CHANGELOG.md, Cargo.toml, README.md
0.7.3 had some panics, rolling 0.7.4 quickly to fix
- fix gaggles to not panic, add test
- fix test_start and test_stop to not panic, add tests
- optimize NNG usage, write directly to Message instead of first to buffer
- fix documentation links
=> release 0.7.4

src/goose.rs, tests/redirect.rs
This sets a boolean to `true` or `false` depending on if there was a redirect, and also stores the final `URL`.
I explored ways to track how many times the request was redirected, and the redirect header(s) used. A custom redirect policy can be defined when building the Reqwest client (https://docs.rs/reqwest/0.10.6/reqwest/redirect/index.html) but I didn't find any way to preserve the redirect information. I explored adding a redirections object within our global CLIENT lazy_static, but we don't have enough information when registering the callback, and the callback can't be async (which we require to unlock the CLIENT object).
Another idea to pursue is to completely disable Reqwests manual handling of redirects, and instead re-implement them in Goose. This may be worth the effort, as …
=> fix #66 track if we redirected

CHANGELOG.md, src/lib.rs
I've confirmed this works through manual testing, but it really should have a test.
Currently Goose only displays statistics to `stdout`, the test would need to process/validate the output.
=> fix #72 properly handle changed success or fail

README.md
README contains invalid code, which result in `mismatched types` error. Fix this, by providing proper example.
=> docs: Fix loadtest example in README

CHANGELOG.md, Cargo.toml, README.md, src/goose.rs, src/lib.rs, src/manager.rs, src/worker.rs, tests/common.rs, tests/redirect.rs
This functionality is required for a client load test ported from Locust.
=> fix #74 optionally make redirects of base_url sticky

src/client.rs, src/goose.rs, src/lib.rs, src/worker.rs
When making GooseClient immutable, I originally moved the mutable elements into a global. This commit reverts that, and instead keeps the GooseClient immutable, using locks to make individual fields mutable where needed.
=> move client and counters out of global into GooseClient

CHANGELOG.md, Cargo.toml, README.md, examples/drupal_loadtest.rs, examples/simple.rs, src/goose.rs, src/lib.rs, src/manager.rs, src/prelude.rs, src/stats.rs, src/user.rs, src/worker.rs, tests/common.rs, tests/gaggle.rs, tests/no_normal_tasks.rs, tests/one_taskset.rs, tests/redirect.rs, tests/setup_teardown.rs
Prior to 0.8.0 we used `client` to refer to both the HTTP client, and individual user threads. With this PR, `GooseClient` is renamed to `GooseUser`, which results in a lot of name changes in nearly every file in the project.
Going forward:
- a User is an individual thread running tasks from a given task set
- a Client is the HTTP client object user's use to make requests
Anyone upgrading from Goose 0.7 to 0.8 will need to update their load tests for this change. For an example on how to upgrade to the new API, review the changes made to `examples/simple.rs` and `examples/drupal_loadtest.rs`.
=> Rename GooseClient to GooseUser

CHANGELOG.md, Cargo.toml, src/goose.rs
Release 0.8.0
- properly subtract previous statistic when handling `set_failure()` and `set_success()`
- detect and track redirects in `GooseRawRequest`
- `--sticky-follow` makes redirect of GooseClient base_url sticky, affecting subsequent requests
- changed `GooseClient` to `GooseUser`
=> release 0.8.0

CHANGELOG.md, Cargo.toml, README.md, src/goose.rs, src/lib.rs, tests/common.rs
- write request logs from parent thread when statistics are received
- convert internal representation of status code from `Option<StatusCode>` to simple `u16`
- document log format
- asynchronously log to file
- include time elapsed since start of load test, and client thread id in logged data
=> fix #42 optionally log all requests to json lines formatted log

Cargo.toml, README.md, src/goose.rs, src/lib.rs, tests/common.rs
The statistics log is intended to be written in JSON Lines format, but was instead simply writing raw Debug output of `GooseRawRequest` structs.
This PR updates the log writing logic to properly format the GooseRawRequest as JSON when writing the log. It also adds support for writing the log in `csv` and `raw` format (the latter being the format it was previously writing the log in).
CSV files are manually crafted, as the csv library with serde support wants to write directly to file and doesn't have async support. As the GooseRawRequest file only has a few different data types this is simple and very fast.
Also adds documentation for the new `--stats-log-format` command line option.
=> actually log in JSON Lines format; also support csv

CHANGELOG.md, README.md
add missing documentation for `--debug-log-format`
=> document --debug-log-format

CHANGELOG.md, Cargo.toml, README.md, src/goose.rs
- `client.log_debug()` will write debug logs to file when specified with `--debug-log-file=`
- add `-debug-log-format=` to switch between `json` (default) and `raw` formats
- cleanup code with clippy, automate clippy with PRs
- add optional compile-time `rustls` feature
=> release 0.8.2

src/lib.rs, tests/one_taskset.rs
I tried to write a test, but I didn't find an easy way, and it's a small fix.
=> fix panic that happens if no host is provided from cli, even if `GooseAttack::set_host` was used.

CHANGELOG.md, examples/drupal_loadtest.rs, src/goose.rs, src/lib.rs, tests/gaggle.rs, tests/logs.rs, tests/no_normal_tasks.rs, tests/one_taskset.rs, tests/redirect.rs, tests/setup_teardown.rs
Splitting out the rename of the outer `response` wrapper into a separate PR, to remove noise/distraction from the functional changes in #97 .
Prior to this change, we referred to the outer wrapper of a GooseResponse as `response`, which is confusing as it also contained a `response` field. This changes referring to the outer wrapper more generically as `goose`, which then contains two fields: `goose.request` and `goose.response`.
=> rename outer response wrapper to goose

README.md, examples/simple.rs
Followup to #98 
Fixes two Missed conversions from `response` wrapper to `goose`.
=> fix two missed conversions from `response` wrapper to `goose`

CHANGELOG.md, Cargo.toml, README.md, examples/drupal_loadtest.rs, src/goose.rs, src/lib.rs, src/throttle.rs, tests/common.rs, tests/logs.rs, tests/redirect.rs, tests/throttle.rs
Initial implementation of requests/second throttle. Fix #90 
- rebased on top of #98 and #99 (splitting out rename of outer `response` wrapper to `goose`)
- return `Result<GooseResponse, Error)` from `goose_send()` to allow a clean and quick shutdown even when the throttle is enabled -- this is an API change, bumping the version from `0.8.y` to `0.9.x`
- throttle implemented with a modified leaky bucket algorithm, when a `GooseClient` makes a request and the throttle is enabled, they have to put a token in the throttle channel before making a request; a dedicated throttle thread removes tokens freeing up space at the desired rate of throttling
- support up to a throttle-rate of 1,000,000 requests per second, keeping the minimum sleep time to ~10ms by removing multiple tokens at a time
- …
=> optionally throttle requests per second

examples/drupal_loadtest.rs, examples/simple.rs, src/goose.rs, src/lib.rs, src/prelude.rs, src/user.rs, tests/gaggle.rs, tests/logs.rs, tests/no_normal_tasks.rs, tests/one_taskset.rs, tests/redirect.rs, tests/setup_teardown.rs, tests/throttle.rs
Tasks must be converted to return `GooseTaskResult`.
This allows the use of `?` as it supports returning a GooseTaskError:
```rust
pub type GooseTaskResult = Result<(), GooseTaskError>;
```
Currently we define 3 errors:
```rust
/// Definition of all errors Goose Tasks can return.
#[derive(Debug)]
pub enum GooseTaskError {
/// Contains any possible Reqwest library error.
Reqwest(reqwest::Error),
/// The request failed.
RequestFailed,
/// The request was canceled (this happens when the throttle is enabled and
/// the load test finished).
RequestCanceled,
}
```
=> return a Result from Task functions

CHANGELOG.md, README.md, examples/drupal_loadtest.rs, examples/simple.rs, src/goose.rs, src/lib.rs, src/prelude.rs, src/stats.rs, src/worker.rs, tests/gaggle.rs, tests/logs.rs, tests/no_normal_tasks.rs, tests/one_taskset.rs, tests/redirect.rs, tests/setup_teardown.rs, tests/throttle.rs
- Return a `Result` from all `GooseAttack` methods that can fail.
- Remove all unnecessary `exit(1)` calls from code, to simplify integrating Goose with other applications.
- This included adding several new `GooseTaskError` types
- Update documentation briefly explaining the use of `Result<>`, `?` and `Ok(())`.
Note: This PR required a considerable number of document tests be rewritten for tests to pass. In order to simplify this process and avoid accidental errors I standardized coding style in all affected comments. Comments for functions that were not affected by this PR will be standardized in a follow up PR.
Fixes #109
=> remove `exit(1)`, instead return error on failure

Cargo.toml, src/goose.rs, tests/common.rs, tests/gaggle.rs, tests/logs.rs, tests/no_normal_tasks.rs, tests/one_taskset.rs, tests/redirect.rs, tests/setup_teardown.rs, tests/throttle.rs
- upgrade to httpmock 4.x
- remove mockito
- rework tests to use a dynamic server port
- rework tests to support parallel execution -- this is a nice performance boost when running tests
- consistently use `assert!()` as `assert_eq!()` and `assert_ne!()` are confusing when reading/debugging tests
Fixes #111
=> upgrade httpmock, two mock frameworks no longer needed

CHANGELOG.md, README.md, src/goose.rs, src/lib.rs, src/logger.rs, src/manager.rs, src/worker.rs
The goal of this PR is to make errors more rich, allowing application developers the option of what they want to display. In our examples, `main()` returns the errors so they are simply displayed.
- enriched `GooseError::InvalidHost`, for example:
```
$ cargo run --example drupal_loadtest -- --host=foo
Finished dev [unoptimized + debuginfo] target(s) in 0.08s
Running `target/debug/examples/drupal_loadtest --host=foo`
Error: InvalidHost { host: "foo", detail: Some("Failure parsing host specified with --host"), parse_error: RelativeUrlWithoutBase }
```
- enriched `GooseError::FeatureNotEnabled`, for example:
```
$ cargo run --example drupal_loadtest -- --worker
Finished dev [unoptimized + debuginfo] target(s) in 0.08s
Running `target/debug/examples/drupal_loadtest --worker`
Error: …
```
=> add more detail to errors

CHANGELOG.md, Cargo.toml
- fix code documentation, requests are async and require await
- properly support setting host when registering task set 
- rename `response` wrapper to `goose`, so we end up with `goose.request` and `goose.response`
- add `--throttle-requests` to optionally limit the maximum requests per second (api change)
- introduce `GooseError` and `GooseTaskError`
- change task function signature, tasks must return a `GooseTaskResult`
- change `GooseAttack` method signatures where an error is possible
- where possible, passs error up the stack instead of calling `exit(1)`
- introduce `GooseAttack.display()` which consumes the load test state and displays statistics
- `panic!()` on unexpected errors instead of `exit(1)`
=> release 0.9.0

CHANGELOG.md, examples/drupal_loadtest.rs, examples/simple.rs, src/goose.rs, src/lib.rs, src/manager.rs, src/prelude.rs, src/stats.rs, src/worker.rs, tests/gaggle.rs, tests/logs.rs, tests/no_normal_tasks.rs, tests/one_taskset.rs, tests/redirect.rs, tests/setup_teardown.rs, tests/throttle.rs
- return `GooseStats` from `GooseAttack.execute()`, a public sub-object contained within `GooseAttack`
- move `GooseStats` to `mod.stats` and rework functions as methods
- consume and display statistics with `goose_stats.print()`
- other methods: `.print_running()`, `.print_requests()`, `.print_response_times()`, `.print_percentiles()` and `.print_status_codes()`
- add test coverage to validate `GooseStats` fields are public
- add test coverage to validate that Goose statistics match server statistics
Fixes #115
=> expose statistics from GooseAttack via GooseStats

CHANGELOG.md, examples/drupal_loadtest.rs, examples/simple.rs, src/lib.rs, src/stats.rs
This is a followup on #116.
- implement `fmt::Display` allowing us to simply `print!("{}", goose_stats);`
- rename methods: `.fmt_requests()`, `.fmt_response_times()`, `.fmt_percentiles()` and `.fmt_status_codes()`
=> Implement fmt::display for GooseStats

CHANGELOG.md, src/goose.rs, src/lib.rs, src/prelude.rs, src/user.rs, tests/one_taskset.rs
This works perfectly now - as proven by the CI runs.
The tests error I first ran into is described in #122 and led to a stack overflow error, but was unrelated to things.
Closes: #76
=> Make it possible to pass closure to GooseTask::new

tests/one_taskset.rs
I feel this is a nice first step into making sure users of the library and tests can create loadtests easier if they all have certain characteristics in common.
The fail output also is pretty useful:
```
---- test_single_taskset_closure stdout ----
thread 'test_single_taskset_closure' panicked at 'response_time_counter != times_called() for item = LoadtestEndpoint {
path: "/",
status: 200,
weight: 9,
}', tests/one_taskset.rs:266:9
```
To give some more motivation, this structure allows in a follow-up and once there are two users to create loadtest tests like this using the builder pattern:
```rust
// Configure endpoints to test.
let test_endpoints = vec![
LoadtestEndpoint {
path: INDEX_PATH,
status_code: 200,
weight: 9,
},
LoadtestEndpoint {
path: ABOUT_PATH,
status_code: 200,
weight: 3, …
```
=> Issue #124: Make test writing more automatic

CHANGELOG.md, Cargo.toml, src/goose.rs
- return `GooseStats` from `GooseAttack` `.execute()`
- rework as methods of `GooseStats`: `.print()`, `.print_running()`, `fmt_requests()`,
`fmt_response_times()`, `fmt_percentiles()`, and `fmt_status_codes()`
- display `GooseStats` with fmt::Display (ie `print!("{}", goose_stats);`)
- make it possible to pass a closure to GooseTask::new
- fix display of `GooseError` and `GooseTaskError`
=> release 0.9.1

CHANGELOG.md, README.md, src/lib.rs, src/stats.rs, tests/common.rs, tests/logs.rs, tests/one_taskset.rs
- change default, renaming `--reset-stats` to `--no-reset-stats`
- display spawn stats if resetting statistics
- modify message if spawning exits early do to `--run-time` expiring
- document in README
- fix #106 
Example with `--run_time` expiring:
```bash
$ cargo run --example simple -- --host http://apache.fosciana/ -t5
Compiling goose v0.9.1-dev (/home/jandrews/devel/rust/goose)
Finished dev [unoptimized + debuginfo] target(s) in 3.60s
Running `target/debug/examples/simple --host 'http://apache.fosciana/' -t5`
------------------------------------------------------------------------------ 
Name                    | # reqs         | # fails        | req/s  | fail/s
----------------------------------------------------------------------------- 
GET /                   | 5              | 0 …
```
=> default to resetting stats, display spawn stats

CHANGELOG.md, tests/gaggle.rs
Only run gaggle tests if the feature is enabled.
Performed web-searches and found https://stackoverflow.com/questions/48583049/run-additional-tests-by-using-a-feature-flag-to-cargo-test to implement.
Fix #121 
With the feature not enabled:
```
$ cargo test gaggle
Running target/debug/deps/gaggle-a993cbffbecd509a
running 1 test
test test_gaggle ... ignored
test result: ok. 0 passed; 0 failed; 1 ignored; 0 measured; 0 filtered out
```
With all features enabled:
```
$ cargo test gaggle --all-features
Running target/debug/deps/gaggle-451ba72b6f1f2257
running 1 test
test test_gaggle ... ok
test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```
And with just the `gaggle` feature enabled:
```
$ cargo test gaggle --features gaggle
Running …
```
=> disable gaggle test if feature isn't enabled

CHANGELOG.md, src/lib.rs, src/throttle.rs, src/util.rs
In smaller load tests the drift is barely perceptible. But in larger tests the drift becomes more pronounced. This PR subtracts the drift from delays in two loops: launching users, and throttling requests.
Fixes #102
=> subtract overhead to avoid time drift

src/user.rs
Not sure what changed, but a recent refactor made the clone unnecessary now.
Maybe the time-drift change? Or the derive Clone on the containing struct?
(I had wanted to try if instead of cloning, pinning would have been enough)
=> Remove no longer needed .clone()

src/lib.rs
This reverts the changes to `--expect-workers` and fixes #143.
With this change:
```
$ cargo run --example drupal_loadtest -- -H http://local.dev/ -t5 -v
Finished dev [unoptimized + debuginfo] target(s) in 0.10s
Running `target/debug/examples/drupal_loadtest -H 'http://local.dev/' -t5 -v`
13:22:29 [ INFO] Output verbosity level: INFO
13:22:29 [ INFO] Logfile verbosity level: INFO
13:22:29 [ INFO] Writing to log file: goose.log
13:22:29 [ INFO] run_time = 5
13:22:29 [ INFO] concurrent users defaulted to 8 (number of CPUs)
```
It correctly throws an error if the `--manager` flag is set w/o defining `--expect-workers`:
```
jandrews@piccolo:~/devel/rust/goose$ cargo run --example drupal_loadtest -- -H http://local.dev/ -t5 -v --manager
Finished dev [unoptimized + debuginfo] target(s) in 0.10s …
```
=> revert --expect-workers changes

CHANGELOG.md, README.md, src/goose.rs, src/lib.rs
- Removed `Option<>` around `error.detail`, as there was only one error that didn't define it yet
- Consistently defined and formatted `error.detail`; errors are now always a complete sentence
- Updated documentation
This fixes #132.
Some sample errors:
```
$ cargo run --example simple -- --worker --host http://foo
Compiling goose v0.10.0-dev (/home/jandrews/devel/rust/goose)
Finished dev [unoptimized + debuginfo] target(s) in 7.87s
Running `target/debug/examples/simple --worker --host 'http://foo'`
Error: InvalidOption { option: "--host", value: "http://foo", detail: "The --host option can not be set together with the --worker flag." }
```
```
$ cargo run --example simple -- --host foo
Finished dev [unoptimized + debuginfo] target(s) in 0.12s
Running `target/debug/examples/simple --host …
```
=> standardize errors for consistency

CHANGELOG.md, Cargo.toml, README.md, src/lib.rs, tests/common.rs
**CHANGES**
- replaced `structopt` with `gumpdrop`, fixing #149 
- gumpdrop doesn't auto-sort options, so this proved a good opportunity to structure options more logically
- added spaces between and headers before grouped options
- renamed "meta" variable names for options with longer names, for example, `--metrics-format <metrics-format>` becomes `--metrics-format FORMAT`, and `--expect-workers <expect-workers>` becomes `--expect-workers VALUE`
- `gumpdrop` moves us closer to addressing #144 as it also parses a slice of &str's the same as parsing run-time-options (it's a non-trivial change to fix completely, so will do in a followup PR)
Compiling on my 8-core laptop with `structopt`:
```
Finished dev [unoptimized + debuginfo] target(s) in 57.51s
real	0m57.551s
user	4m8.621s
sys …
```
=> convert from structopt to gumpdrop

CHANGELOG.md, src/lib.rs, src/prelude.rs, tests/one_taskset.rs
The prelude documentation had gotten out of date. This PR updates it with what's actually defined in `src/prelude.rs`.
Fixes #134
=> update prelude documentation

CHANGELOG.md, src/goose.rs, src/lib.rs, src/manager.rs, src/worker.rs, tests/common.rs, tests/gaggle.rs, tests/logs.rs, tests/no_normal_tasks.rs, tests/one_taskset.rs, tests/redirect.rs, tests/setup_teardown.rs, tests/throttle.rs
Consistently build configuration from arguments:
- remove cases where parameters were manually modified directly in the configuration object
- remove cases where defaults were automagically derived
This fixes #144.
=> consistently build configuration from arguments

src/goose.rs, src/lib.rs, src/user.rs
The `GooseUser` object didn't have direct access to the `GooseTask` name if set. The old implementation was essentially caching the last seem task name, but this wasn't working correctly. Instead I've re-worked the logic so we pass the actual `GooseTask` name to the `GooseUser` when building a weighted list of tasks for the user.
Now statistics are being generated exactly as expected, and the documentation can be properly updated for the [0.10.0 release](https://github.com/tag1consulting/goose/pull/160). Fixes #161 
Running the example load test generates the following statistics, and all the numbers now match up correctly as expected:
```
=== PER TASK METRICS ===
------------------------------------------------------------------------------
Name                     |   # times run | …
```
=> fix statistics with GooseTask name

CHANGELOG.md, src/lib.rs, src/manager.rs, src/worker.rs, tests/defaults.rs, tests/gaggle.rs
Rework `hatch_rate` implementation so it's stored in an `Option<usize>` as it can be `None` on the Worker (where it then inherits the setting from the Manager). We use an `Option` instead of just a `usize` that defaults to `0` so we can detect even an invalid configuration of `--hatch-rate 0` on the Worker.
If not otherwise configured and not on a Worker, `hatch_rate` defaults to `Some(1)`. 
Fixes #163.
=> rework hatch_rate with Option<usize>

CHANGELOG.md, src/lib.rs, src/manager.rs
Fixes #166. The `GooseAttack.users` field was redundant and unnecessary.
(This also adds `defaults` validation for `users` that should also be added in #165 for `hatch_rate` -- I'll update that PR shortly.)
=> remove `GooseAttack.users`

README.md
Fixes #170 
Properly format list in `Default` section:
The following defaults can be configured with a `&str`:
- host: `GooseDefault::Host`
- log file name: `GooseDefault::LogFile`
- metrics log file name: `GooseDefault::MetricsFile`
- metrics log file format: `GooseDefault::MetricsFormat`
- debug log file name: `GooseDefault::DebugFile`
- debug log file format: `GooseDefault::DebugFormat`
- host to bind Manager to: `GooseDefault::ManagerBindHost`
- host for Worker to connect to: `GooseDefault::ManagerHost`
The following defaults can be configured with a `usize` integer:
- total users to start: `GooseDefault::Users`
- users to start per second: `GooseDefault::HatchRate`
- number of seconds for test to run: `GooseDefault::RunTime`
- log level: `GooseDefault::LogLevel`
- verbosity: …
=> fix formatting of `Default` section in README

src/goose.rs
Fixes #176 by mentioning `--sticky-follow` in the `set_base_url()` documentation.
=> mention --sticky-follow in set_base_url() docs

CHANGELOG.md, src/lib.rs, src/worker.rs
Properly register shutdown pipe handler if the load test times out or is canceled, preventing a panic.
Prior to this change:
```bash
^C06:13:48 [ WARN] caught ctrl-c, stopping...
06:13:49 [ INFO] [2] stopping after 58 seconds...
06:13:49 [ INFO] [2] waiting for users to exit
06:13:49 [ INFO] [2] exiting user 3 from AnonBrowsingUser...
06:13:49 [ INFO] [2] exiting user 1 from AnonBrowsingUser...
06:13:49 [ INFO] [2] exiting user 4 from AnonBrowsingUser...
06:13:49 [ INFO] [2] exiting user 2 from AnonBrowsingUser...
thread '<unnamed>' panicked at '[2] manager went away, exiting', src/worker.rs:29:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
Aborted (core dumped)
```
After this change:
```bash …
```
=> register shutdown pipe handler on shutdown

CHANGELOG.md, src/manager.rs
The `goose_attack.started` timestamp wasn't getting reset after all Workers start, resulting in some confusing metrics and debug output. This PR properly resets the timestamp when all Workers start.
Fixes #171
=> reset goose_attack.started once all workers start

CHANGELOG.md, Cargo.toml, README.md
Release `0.10.1`.
- rework `hatch_rate` to be stored in an `Option<usize>` as it can be `None` on a Worker
- remove redundant `GooseAttack.users` instead using the `Option<usize>` in `configuration`
- improve bounds handling of defaults, generate errors for invalid values
- properly handle early shutdown of Gaggle distributed load test from Worker process
- Manager starts timing Gaggle distributed load test only after all Workers start
=> Tag 0.10.1 for release

CHANGELOG.md, src/lib.rs
Remove unnecessary data from `GooseAttack` structure, fixing #179.
=> remove GooseAttack.number_of_cpus

Cargo.toml, tests/redirect.rs
Continuing what was started in #175, this de-duplicates and adds Gaggle tests for `tests/redirect.rs`.
There are three distinct tests in this integration test file, and all of them logically need their own Gaggle versions. [I reached out to the `httpmock` author](https://github.com/alexliesenfeld/httpmock/issues/15) to ask if there was a way to serialize some tests in a single file, and he pointed me to the [`serial_test` module](https://crates.io/crates/serial_test), which this PR also adds.
=> add Gaggle versions of all redirect integration tests

tests/setup_teardown.rs
Continuing what was started in #175, this de-duplicates and adds Gaggle tests for `tests/setup_teardown.rs`.
There is a big @FIXME in the code as until #182 lands the Gaggle functionality isn't working correctly.
=> deduplicate setup_teardown test, add gaggle versions

CHANGELOG.md, src/lib.rs, src/manager.rs, tests/redirect.rs, tests/setup_teardown.rs
Fixes #182 
- split out `test_start` and `test_stop` logic into helper functions
- invoke `run_test_start` and `run_test_stop` as Manager
- remove special-handling for `test/setup_teardown.rs` confirming `test_start` and `test_stop` are the same in standalone and Gaggle mode
Note: `test/redirect.rs` incorrectly suggests there's a difference between standalone and Gaggle mode, but this was a misunderstanding of the problem. This will instead be addressed in #186
=> properly invoke test_start and test_stop in Gaggles

CHANGELOG.md, src/lib.rs, tests/redirect.rs
- fixes #186 
- cleanup inline documentation around `on_start` as the sticky redirect test was making a bad assumption
- rework sticky redirect tests to properly confirm each GooseUser thread correctly loads the redirect; remove TODO
=> properly test sticky redirect

CHANGELOG.md, src/worker.rs, tests/sequence.rs
Add a test to confirm `set_sequence()` on tasks works as expected, affecting the order tasks are executed. This leverages that by default Goose executes tasks in the order they are declared, combined with a task that sleeps for the duration of the test after which no other tasks run. Without sequences all tasks run, as the delay task runs last. With sequences only two tasks run, as the delay task runs sooner.
Also confirms that sequences do not affect `test_start` and `test_stop` functions, which should always run regardless.
=> add a test for task sequencing

CHANGELOG.md, src/manager.rs, src/worker.rs, tests/closure.rs, tests/common.rs, tests/defaults.rs, tests/logs.rs, tests/no_normal_tasks.rs, tests/one_taskset.rs, tests/redirect.rs, tests/sequence.rs, tests/setup_teardown.rs, tests/throttle.rs
Restructures tests to re-use code where possible, also moving some common code into `tests/common.rs`. De-duplicates the code to fix #133 and ensures all functionality is tested both in Standalone and Gaggle mode.
=> deduplicate code in tests

CHANGELOG.md, src/lib.rs, tests/logs.rs
- use `Worker` configuration in `GooseUser` when running in `Gaggle` mode
- remove debug logs committed while identifying this problem
- enable Gaggle tests for debug logging
- fixes #194
=> fix debug logging in Gaggle mode

CHANGELOG.md, Cargo.toml, README.md
- fixup sticky redirect tests to properly test functionality
- add `test/sequence.rs` to confirm sequencing tests works correctly, even in Gaggle mode
- deduplicate test logic by moving shared functionality into `tests/common.rs`; consistently test functionality both in standalone and Gaggle mode
- properly create debug log when enabled in Gaggle mode
=> release 0.10.3

CHANGELOG.md, Cargo.toml, examples/umami/README.md, examples/umami/common.rs, examples/umami/english.rs, examples/umami/main.rs, examples/umami/spanish.rs
- Introduces a new, more complicated example
- Performs a load test of Drupal 9's Umami demo install profile
This is a load test for Drupal's Umami Profile, which is included as part of Drupal 9 core. In order to use this load test, you must first install the Umami Profile as documented here:
https://www.drupal.org/docs/umami-drupal-demonstration-installation-profile
The load test was developed using a locally hosted Drupal 9 install hosted in a DDEV container:
https://www.ddev.com/
By default it will try and load pages from https://drupal-9.0.7.ddev.site/.
The load test is split into the following files:
- `main.rs`: This file contains the main() function and defines the actual load test;
- `common.rs`: This file contains helper functions used by the task functions;
- `english.rs`: This …
=> add example testing Drupal 9 Umami install profile

CHANGELOG.md, Cargo.toml, src/lib.rs
We have no specific need to use `TermLogger`, and can instead always use `SimpleLogger`. We lose terminal coloring, but afaik that's not an important feature. This also seems to resolve the issues around double-initializing the logger. Attempts to initialize the logger twice result in a friendly INFO log and the process continues without errors:
```
07:13:24 [ INFO] failed to initialize CombinedLogger: attempted to set a logger after the logging system was already initialized
```
- replace TermLogger with SimpleLogger so Goose can be run with or without a TTY
- fixes #202 
- fixes #122
=> replace TermLogger with SimpleLogger

examples/umami/README.md, examples/umami/admin.rs, examples/umami/main.rs
Each admin load test user logs in one time at the start of the test and then runs the following tasks (and also load all static elements on any pages loaded):
- Loads the front page;
- Loads the article listing page;
- Loads an "article", edits (not making any actual changes), and saves it (flushing all caches).
=> add logged in admin user to umami load test

CHANGELOG.md, src/lib.rs, src/manager.rs, src/worker.rs, tests/defaults.rs, tests/one_taskset.rs
Reverts tag1consulting/goose#214
Causes intermittent test failures in Github Actions
=> Revert "by default reset metrics after all Workers start in Gaggle mode"

CHANGELOG.md, src/lib.rs, src/manager.rs, src/util.rs, src/worker.rs, tests/defaults.rs
Currently the slowest rate to hatch users is 1 per second. With this PR, hatch rate can be specified as a f32, so for example you can say `-r.5` and it will launch 1 user every 2 seconds.
=> support f32 hatch rate

CHANGELOG.md, Cargo.toml, README.md
- support floating point hatch rate (ie, hatch 1 user every 2 seconds with `-r .5`)
=> release 0.10.5

CHANGELOG.md, README.md, src/lib.rs, src/manager.rs, tests/defaults.rs
Disables running metrics by default.
Makes time between running metrics configurable.
For example, to display running statistics every 2 seconds:
`--running-metrics 2`
Or to make this the default in your load test:
```rust
GooseAttack::initialize()?
.register_taskset(taskset!("LoadtestTasks")
.register_task(task!(loadtest_task))
)
.set_default(GooseDefault::RunningStatistics, 2)?
.execute()?
```
=> replace `--only-summary` with `--running-metrics`

CHANGELOG.md, README.md, src/lib.rs, src/prelude.rs, tests/scheduler.rs
- allow configuration of the algorithm used when allocating `GooseTaskSet`s to starting `GooseUser`s:
- `GooseScheduler::RoundRobin` allocates 1 of each available `GooseTaskSet` at a time (new default)
- `GooseScheduler::Serial` allocates all of each available `GooseTaskSet` in the order they are defined
- `GooseScheduler::Random` randomly allocates 1 `GooseTaskSet` at a time from all available
- fixes #221
=> expose GooseScheduler for allocating GooseTaskSets

CHANGELOG.md, src/goose.rs, src/lib.rs, src/manager.rs, src/metrics.rs, src/util.rs, src/worker.rs, tests/defaults.rs, tests/redirect.rs, tests/scheduler.rs
- when enabled, display running metrics during the entire load test (even when starting up and/or shutting down)
-  split the function that launches the load test into smaller logical pieces, wrapping it all in a loop to allow regular display of metrics
- put all variables required to run a load test into a GooseAttackRunState structure which can be efficiently passed around
- fixes #224 
- fixes #136
=> display running metrics when enabled during ramp-up, running, and shutdown

CHANGELOG.md, Cargo.toml, README.md
- replace `--only-summary` with `--running-metrics <usize>`, running metrics are disabled by default
- allow configuration of the algorithm used when allocating `GooseTaskSet`s to starting `GooseUser`s:
o `GooseTaskSetScheduler::RoundRobin` allocates 1 of each available `GooseTaskSet` at a time (new default)
o `GooseTaskSetScheduler::Serial` allocates all of each available `GooseTaskSet` in the order they are defined
o `GooseTaskSetScheduler::Random` allocates 1 random `GooseTaskSet` from all available
- when enabled, display running metrics for the entire duration of test, including ramp-up and shutdown
=> release 0.10.6

CHANGELOG.md, src/lib.rs
- when setting `--running-metrics <usize>` the intent is that the running metrics are displayed every usize seconds
- the Goose parent thread collects metrics from all GooseUser threads, and this takes some time (especially on bigger load tests)
- it also displays running metrics when enabled
- this PR subtracts the time spent doing these "other things" before running through the loop and doing it all over again, avoiding all but the most extreme time drifts
- this also seems to fix some intermittent integration test failures that were inconsistently happening
=> account for time spent not sleeping, looping every second

CHANGELOG.md, src/logger.rs
- increases the buffer size for the debug log from 8K to 8M
- adds line feed at start of each debug file line instead of the end in case a web page is ever larger than the buffer
- fixes https://github.com/tag1consulting/goose/issues/220
=> increase debug log buffer size

CHANGELOG.md, README.md, src/goose.rs, src/lib.rs, src/logger.rs, tests/defaults.rs
- introduce `--no-debug-body` to optionally not log the response body in the debug log
- allocate less memory to the debug log buffer when not logging response bodies (64K versus 8M)
- fixes https://github.com/tag1consulting/goose/issues/230
=> optionally don't log response body in debug log

CHANGELOG.md, README.md, src/lib.rs, src/worker.rs, tests/defaults.rs, tests/logs.rs, tests/throttle.rs
- Goose can optionally generate a log of all requests it makes, which is confusingly referred to as the "metrics file"; this PR renames it more accurately to the "requests file"
- rename `--metrics-file` to `--requests-file`
- rename `--metrics-format` to `--requests-format`
- fixes #226
=> rename metrics file to requests file

CHANGELOG.md, src/lib.rs
- merge the two drift timers into a single `drift_timer` variable
- create `set_run_phase` helper to consistently reset drift timer any time the phase changes
- fixes #239 
- lays some of the ground work for dynamically changing the run phase
=> merge drift timers; reset timer with helper when phase changes

CHANGELOG.md, Cargo.toml, README.md, src/goose.rs
- account for time spent doing things other than sleeping, maintaining more consistency when displaying statistics and shutting down
- start each debug log file with a line feed in case the page is too big for the buffer; increase the debug logger buffer size from 8K to 8M.
- introduce `--no-debug-body` flag to optionally prevent debug log from including the response body
- rename the metrics file to requests file to better reflect what it is
o `--metrics-file` becomes `--requests-file`
o `--metrics-format` becomes `--requests-format`
o `GooseDebug::MetricsFile` becomes `GooseDebug::RequestsFile`
o `GooseDebug::MetricsFormat` becomes `GooseDebug::RequestsFormat`
- reset drift timer any time the attack_phase changes
- document all public high level files and functions
=> release 0.10.7

CHANGELOG.md, Cargo.toml, src/goose.rs, src/lib.rs, src/logger.rs, src/throttle.rs, src/user.rs, src/util.rs, tests/scheduler.rs, tests/sequence.rs, tests/throttle.rs
- upgrade dependency to [`tokio`](https://docs.rs/tokio/1.2.0/tokio) 1
- upgrade dependency to [`reqwest`](https://docs.rs/reqwest) 0.11
- Fixes #204 
- Re-opens #205 
- Replaced Tokio's [`mpsc`](https://docs.rs/tokio/*/tokio/sync/mpsc/index.html) sync implementation with [`flume`](https://docs.rs/flume) based on feedback from @Darksonn in https://github.com/tokio-rs/tokio/issues/3350#issuecomment-773952897 (which improved the accuracy of the throttle and required an adjustment to the throttle gaggle test assertions)
I ran some performance comparisons, confirming that updating to Tokio 1.x and switching to Flume didn't cause any performance regressions: https://docs.google.com/spreadsheets/d/1T9SsgveIm1JFRvTcTFWBSPgweBthYiR5apmyHdb92eA/edit#gid=0  (It seems to be consistently slightly …
=> Upgrade to Tokio 1.x

CHANGELOG.md, examples/umami/README.md, examples/umami/main.rs
Update umami example to suggest any version of Drupal 9, not just Drupal 9.0.7. (Changes to later versions of the Umami install profile may require setting a minimum version at some time.)
=> update umami example for any version of Drupal 9

CHANGELOG.md, src/goose.rs, src/lib.rs, src/manager.rs
Fixes #252 
The Manager process allocates a bunch of GooseUser objects that are never actually used, they are re-allocated on the Workers. This PR is an optimization to avoid doing duplicate/wasted work.
- Don't allocate unnecessary GooseUser objects when determining which users get sent to Workers
- Thanks to [this thread](https://users.rust-lang.org/t/serde-cbor-very-slow-when-used-for-saving-and-loading-game-maps/36308/7) perform serde_cbor serialization in a BufWriter, drastically optimizing it
=> optimize time it takes to start a Gaggle

CHANGELOG.md, src/lib.rs, src/manager.rs, src/worker.rs
I originally assumed (incorrectly) that we weren't properly setting `hatch_rate` on the Workers. Instead what's happening is we're pushing metrics from the Workers to the Manager too frequently, and when running as a Gaggle we end up blocking waiting for the Manager to reply.
To solve:
- We make the Manager wake every 100ms instead of ever 500ms (so we minimize how often we block)
- We only synchronize the metrics at least as often as we display metrics, or at least once every five seconds
- We optimize serialization with `serde_cbor` by using a BufWriter
Fixes #253
=> respect hatch rate when launching gaggle

CHANGELOG.md, README.md, src/lib.rs
Fixes #184 
Add links to online documentation.
- [README](https://github.com/tag1consulting/goose/blob/main/README.md)
- [Developer documentation](https://docs.rs/goose/)
- [Blogs and more](https://tag1.com/goose/)
- [Goose vs Locust and jMeter](https://www.tag1consulting.com/blog/jmeter-vs-locust-vs-goose)
- [Real-life load testing with Goose](https://www.tag1consulting.com/blog/real-life-goose-load-testing)
- [Gaggle: a distributed load test](https://www.tag1consulting.com/blog/show-me-how-flock-flies-working-gaggle-goose)
- [Optimizing Goose performance](https://www.tag1consulting.com/blog/golden-goose-egg-compile-time-adventure)
=> add documentation links

CHANGELOG.md, src/goose.rs, src/lib.rs, src/manager.rs, src/metrics.rs, src/report.rs, src/worker.rs, tests/error.rs
Capture errors and display an error summary in the metrics report at the end of the load test. (Example below). Enabled by default, can be disabled with `--no-error-summary` or by setting `GooseDefault::NoErrorSummary` to `true`.
If there are any error when `--report--file` is configured, errors are included in the HTML report.
When running in Gaggle mode, errors triggered by Workers are aggregated by the Manager and included in any reports.
Fixes #245 
Example:
```
=== PER TASK METRICS ===
------------------------------------------------------------------------------
Name                     |   # times run |        # fails |   task/s |  fail/s
------------------------------------------------------------------------------
1: AnonBrowsingUser      |
1: (Anon) front page   |           150 …
```
=> count and aggregate errors, display with metrics

CHANGELOG.md, Cargo.toml, README.md, examples/umami/common.rs, src/goose.rs, src/lib.rs, src/manager.rs, src/metrics.rs, src/user.rs, src/worker.rs, tests/closure.rs, tests/defaults.rs, tests/error.rs, tests/logs.rs, tests/no_normal_tasks.rs, tests/one_taskset.rs, tests/redirect.rs, tests/scheduler.rs, tests/sequence.rs, tests/setup_teardown.rs, tests/throttle.rs
- fixes #262, following the Rust naming conventions in regards to case as defined in https://rust-lang.github.io/api-guidelines/naming.html#casing-conforms-to-rfc-430-c-case
- uses a custom display format to display methods so the name continues to be all caps as expected, for example `GET` instead of `Get`
- removes a lingering `panic!()` that was incorrectly formatted for Rust 2021, replacing it with a correctly formatted error
- optimize vector creation by avoiding creating a mutable vector then pushing data multiple times, instead using the more performant and easier to read `vec![]` macro (https://rust-lang.github.io/rust-clippy/master/index.html#vec_init_then_push)
- call `format!` directly in closure test for improved readability
=> prepare for Rust 2021

CHANGELOG.md, Cargo.toml, examples/drupal_loadtest.rs, src/user.rs
- Update `rand` to the latest `0.8` branch
- Requires update to how the [`gen_range`](https://docs.rs/rand/0.8.*/rand/trait.Rng.html#method.gen_range) method is invoked
=> update rand dependency to 0.8 branch

CHANGELOG.md, Cargo.toml
- use `1.0` instead of `1.0.0-rc1`
- fixes `gaggle` compilation on Mac ARM64
=> update optional `nng` dependence for `gaggle` feature

CHANGELOG.md, README.md, src/goose.rs, src/lib.rs, src/prelude.rs, src/user.rs, tests/scheduler.rs, tests/sequence.rs
Prior to this PR, Goose's Task scheduler is a bit complex: it maintains pointers to multiple buckets (tracking sequenced tasks versus unsequenced tasks), and initially allocates `GooseTask`s sequentially as they're defined, and subsequently shuffles them each time they're re-run.
With this PR, each `GooseUser` schedules their `GooseTask`s one time at startup, and then repeatedly runs the tasks over and over in the same order. It allocates `GooseTask`s based on the configured `GooseScheduler`, so either `RoundRobin`, `Sequential`, or `Random`, defaulting to `RoundRobin` if not otherwise configured. The primary goal of this change is to ensure that load tests are consistent from run to run; general simplification was just a bonus.
(When writing …
=> respect GooseScheduler when allocating GooseTasks

CHANGELOG.md, Cargo.toml, README.md, build.rs
- document and enforce minimum `rustc` version of `1.49.0`
- fixes #265
- goose depends on [`flume`](https://docs.rs/flume) for communication between threads, which in turn depends on [`spinning_top`](https://docs.rs/spinning_top) which uses `hint::spin_loop` which stabilized in `rustc` version `1.49.0`. More detail in https://github.com/rust-lang/rust/issues/55002.
In the event that goose is compiled with an earlier version of `rustc` it will fail and provide a helpful error:
```
Compiling goose v0.11.1-dev (~/goose)
error: failed to run custom build command for `goose v0.11.1-dev (~/goose)`
Caused by:
process didn't exit successfully: `~/goose/target/release/build/goose-0b1c363936c37b47/build-script-build` (exit code: 1)
--- stderr
goose dependency `flume` depends on `spinning_top` …
```
=> document and enforce minimum `rustc` requirement of `1.49.0`

CHANGELOG.md, Cargo.toml, README.md, src/goose.rs
- update [`rand`](https://docs.rs/rand) dependency to `0.8` branch, update [`gen_range`](https://docs.rs/rand/0.8.*/rand/trait.Rng.html#method.gen_range) method call
- update dependencies: [`itertools`](https://docs.rs/itertools) to `0.10`, [`simplelog`](https://docs.rs/simplelog) to `0.10`, [`url`](https://docs.rs/url) to `2`
- update [`nng`](https://docs.rs/nng) dependency for optional `gaggle` feature
- simplify [`examples/umami`](https://github.com/tag1consulting/goose/tree/main/examples/umami) regex when parsing form
- allow configuration of algorithm for allocating `GooseTask`s the same as `GooseTaskSet`s; `GooseTaskSetScheduler` becomes more generically `GooseScheduler`
- specify (and detect) minimum `rustc` requirement of `1.49.0`, due to [`flume`](https://docs.rs/flume) …
=> release v0.11.1

CHANGELOG.md, Cargo.toml, README.md, src/controller.rs, src/lib.rs
- introduce WebSocket Controller allowing real-time control of load test, optionally disable with `--no-websocket`, supports the following commands:
o `exit` (and `quit`) exit the WebSocket Controller
o `stop` stops the running load test (and exits the controller)
o `hatchrate` (and `hatch_rate`) FLOAT sets per-second rate users hatch
o `config` returns the current load test configuration in json format
o `metrics` (and `stats`) returns metrics for the current load test in json format
- WebSocket Controller bind host defaults to `0.0.0.0`, can be configured with `--websocket-host`
- WebSocket Controller bind port defaults to `5117`, can be configured with `--websocket-port`
- WebSocket Controller defaults can be changed:
o default to not enabling WebSocket Controller: …
=> introduce a WebSocket Controller

CHANGELOG.md, README.md, src/controller.rs, src/lib.rs, src/util.rs
- make it possible to start and stop a load test without completely restarting Goose
- introduce `--no-autostart` to disable automatically starting the load test, leaves Goose in an idle state waiting for Controller commands
o renamed `stop` Controller command to `shutdown`
o added new `start` Controller command, telling idle Goose load test to start
o added new `stop` Controller command, telling starting or running Goose load test to stop and return to an idle state
- consolidation of logic to properly support Controller fixed a bug where metrics wouldn't display and the debug file, request file, and html report weren't written when load test was stopped while still launching users
- regularly sync metrics, using a timeout to avoid hanging the main loop
- properly reset metrics when load …
=> support starting, stopping, and restarting load test through Controller

CHANGELOG.md, Cargo.toml, README.md, src/controller.rs, src/lib.rs
- use traits to de-duplicate code where possible, and to gain compile-time validation that both Controllers are properly handling all defined commands
- add `async_trait` dependency as Stable Rust doesn't otherwise support async traits
- add `GooseController` trait:
o add `get_command_string()` providing controller-specific logic for extracting a command from the protocol-specific request
- add `GooseControllerExecuteCommand` trait:
o add `execute_command()` to run the command received from a Controller request
o add `write_to_socket()` to implement the per-protocol logic for sending a message back to the controller client
- introduce `GooseControllerState` created in the main Controller thread and then passed to the per-client thread as new requests come in, also provides the following …
=> [WIP] add traits to improve compile-time validation

CHANGELOG.md, README.md, src/controller.rs, src/lib.rs, src/util.rs
Introduce the following Controller commands:
- `host HOST`: set host to load test, ie http://localhost/ (can only be set when load test is idle); matches any of `host`, `hosts`, `hostname`, `host-name` and `host_name`
- `users INT`: set number of simulated users (can only be set when load test is idle); matches `user` and `users` both
- `runtime TIME`: set how long to run test, ie 1h30m5s (can be set even when load test is running); matches  any of `runtime`, `run_time`, `run-time` and `run`
- move `is_valid_host()` into mod `util` and also call it from the Controller
- added developer documentation on the steps necessary to add a new command
=> add new commands: host, users, runtime

CHANGELOG.md, README.md, src/controller.rs, src/lib.rs
- make it possible to start Goose without setting a host if `--no-autostart` is enabled
- do not allow `no_autostart` with both `no_telnet` and `no_websocket` as a Controller is required if not automatically starting the load test
- properly set `no_autostart`, `no_telnet` and `no_websocket` from defaults
=> don't require host when --no-autostart enabled

CHANGELOG.md, Cargo.toml, README.md, src/goose.rs
- introduce telnet Controller allowing real-time control of load test, optionally disable with `--no-telnet`, supports the following commands:
o `help` (and `?`) display help
o `exit` (and `quit`) exit the telnet Controller
o `shutdown` shuts down the running load test (and exits the controller)
o `host` (and `hosts`) HOST sets host to load test against, ie http://localhost/
o `users` (and `user`) INT sets number of simulated users
o `hatchrate` (and `hatch_rate`) FLOAT sets per-second rate users hatch
o `runtime` (and `run_time`) TIME sets how long the load test should run
o `config` displays the current load test configuration
o `config-json` displays the current load test configuration in json format
o `metrics` (and `stats`) displays metrics for the current load test
o `metrics-json` …
=> prepare 0.11.2

CHANGELOG.md, src/controller.rs, src/lib.rs, src/logger.rs, src/metrics.rs, src/util.rs
While reviewing the latest [Goose docs](https://docs.rs/goose) I noticed it's a bit cluttered with functions and structures that aren't useful to consumers of the Goose library. In those cases I've changed their scope from `pub` to `pub(crate)` thereby removing them from the documentation.
- documentation cleanup
- de-scope internal-only documentation from docs.rs
- improve public-facing documentation and provide more and better examples
=> make internal shared funcs and structs pub(crate)

CHANGELOG.md, README.md, src/lib.rs, src/logger.rs, src/manager.rs, src/metrics.rs, src/report.rs, src/worker.rs, tests/logs.rs
- introduce `--error-file` run-time option for logging `GooseErrorMetric`s to file
- introduce `--error-format` for changing the format of the error log
- renamed `GooseErrorMetric` to `GooseErrorMetricAggregate` matching other metrics
- introduced new `GooseErrorMetric` object used for writing the error log
@TODO: tests
=> introduce --error-file and --error-format

CHANGELOG.md, README.md, src/goose.rs, src/lib.rs, src/logger.rs, src/metrics.rs, src/user.rs, src/worker.rs, tests/defaults.rs, tests/logs.rs, tests/throttle.rs
It was confusing that `requests` and `tasks` were plural, while `error` was singular. It was also confusing what `--log-file` was compared to the many other log files Goose can generate, so lots of renaming for consistency:
- renamed `--log-file` to `--goose-log`, `--requests-file` to `--request-log`, `--requests-format` to `--request-format`, `--tasks-file` to `--task-log`, `--tasks-format` to `--task-format`, `--error-file` to `--error-log`, and `--debug-file` to `--debug-log`
=> more consistent log names

README.md, src/goose.rs, src/lib.rs, src/logger.rs, src/metrics.rs
Marking Coordinated Omission Mitigation an experimental feature and disabling it by default. Hopefully the reported issues/and feedback can be addressed satisfactorily enough to enable it by default in a future release.
- also renamed `coordinated_omission_cadence` to `user_cadence` to make it more clear what the value is tracking when --co-mitigation is enabled
=> disable experimental co-mitigation by default

CHANGELOG.md, Cargo.toml, README.md, src/lib.rs
- remove internal-only functions and structures from documentation, exposing only what's useful to consumers of the Goose library (API change)
o `goose::initialize_logger()`, `Socket` reduced to `pub(crate)` scope
o `goose::controller::GooseControllerProtocol`, `GooseControllerRequestMessage`, `GooseControllerResponseMessage`, `GooseControllerRequest`, `GooseControllerResponse`, `GooseControllerState`, `::controller_main()` reduced to `pub(crate)` scope
o `goose::manager::manager_main()` reduced to `pub(crate)` scope
o `goose::metrics::GooseRequestMetric::new()`, `::set_final_url()`, `::set_response_time()`, and `::set_status_code()`, `::per_second_calculations()`, `format_number()`, `merge_times()`, `update_min_time()`, `update_max_time()`, `calculate_response_time_percentile()`, and …
=> release v0.12.0

Cargo.toml
Note: even with this change I still end up with `openssl` in my `cargo tree`:
```
├── goose v0.11.2 (/home/medwards/forks/goose)
<snip>
│   ├── tokio-tungstenite v0.14.0
<snip>
│   │   ├── tokio v1.8.1 (*)
│   │   ├── tokio-rustls v0.22.0 (*)
│   │   ├── tungstenite v0.13.0
<snip>
│   │   │   ├── native-tls v0.2.7
│   │   │   │   ├── log v0.4.14 (*)
│   │   │   │   ├── openssl v0.10.32
│   │   │   │   │   ├── bitflags v1.2.1
│   │   │   │   │   ├── cfg-if v1.0.0
│   │   │   │   │   ├── foreign-types v0.3.2
│   │   │   │   │   │   └── foreign-types-shared v0.1.1
│   │   │   │   │   ├── lazy_static v1.4.0
│   │   │   │   │   ├── libc v0.2.95
│   │   │   │   │   └── openssl-sys v0.9.63
│   │   │   │   │       └── libc v0.2.95
│   │   │   │   │       [build-dependencies]
│   │   │   │   │ …
```
=> Propagate `rustls` feature to `tokio-tungstenite`

CHANGELOG.md, Cargo.toml, README.md, tests/controller.rs
- start with #321
- update `tungstenite` to `0.14` and `tokio-tungstenite` = "0.15"
- add `rustls` as development dependency for `tests/controller.rs`
- rename Goose `rustls` feature to `rustls-tls` as feature and library can't share the same name
=> update tungstenite so it's possible to build without openssl

tests/controller.rs
- fix to compile on Linux
I'm currently developing on Mac OS X, and realized that it _never_ has OpenSSL. When I tested on Linux I realized Goose no longer compiled: fixed.
Goose should be testing more targets to catch this.
On Linux, with the `rustls-tls` feature enabled:
```
jandrews@goose:~/loadtest-test$ cargo tree | grep openssl
│   │   │   ├── openssl-probe v0.1.4
jandrews@goose:~/loadtest-test$ cargo tree | grep tls
│   ├── hyper-rustls v0.22.1
│   │   ├── rustls v0.19.1
│   │   ├── tokio-rustls v0.22.0
│   │   │   ├── rustls v0.19.1 (*)
│   ├── rustls v0.19.1 (*)
│   ├── tokio-rustls v0.22.0 (*)
│   ├── rustls v0.19.1 (*)
│   ├── tokio-rustls v0.22.0 (*)
│   │   ├── rustls v0.19.1 (*)
│   │   ├── rustls-native-certs v0.5.0
│   │   │   └── rustls v0.19.1 (*)
```
And without the …
=> fix to compile on Linux

CHANGELOG.md, src/lib.rs
- always configure `GooseConfiguration.manager` and `GooseConfiguration.worker`
- confirm Manager is enabled when setting `--expect-workers`
- fixes #292
=> Manager requires ExpectWorkers

CHANGELOG.md, Cargo.toml, README.md
- rename `rustls` feature to `rustls-tls` so `tests/controller.rs` can build with the `rustls` library; update `tungstenite` to `0.14` and `tokio-tungstenite` = `0.15` to allow building with `rustls`
- documentation cleanup; properly rename `GooseDefault::RequestFormat` and fix links
- always configure `GooseConfiguration.manager` and `GooseConfiguration.worker`; confirm Manager is enabled when setting `--expect-workers`
- moved `GooseConfiguration`, `GooseDefault`, and `GooseDefaultType` into new `src/config.rs` file; standardized configuration precedence through internal `GooseConfigure` trait defining `get_value()` for all supported types; general improvements to configuration documentation
=> release 0.12.1

CHANGELOG.md, Cargo.toml, src/config.rs, src/goose.rs
- enable [`gzip`](https://docs.rs/reqwest/*/reqwest/struct.ClientBuilder.html#method.gzip) support in the http client
- can be disabled with `--no-gzip` or `GooseDefault::NoGzip`
- documented how to manually enable [`deflate`](https://docs.rs/reqwest/*/reqwest/struct.ClientBuilder.html#method.deflate) and/or [`brotli`](https://docs.rs/reqwest/*/reqwest/struct.ClientBuilder.html#method.brotli) compression
=> enable gzip and deflate in http client

CHANGELOG.md, Cargo.toml, README.md, examples/umami/admin.rs, examples/umami/common.rs, src/config.rs, src/goose.rs, src/logger.rs, src/metrics.rs
- add all client request `headers` to the `GooseRequestMetric`, so they are included in the request log and the debug log
- introduce `GooseRawMetric` which contains the `method`, `url`, `headers` and `body` of the client request made, and is now contained in `raw` field of the `GooseRequestMetric` (API change)
- introduce `--request-body` (and `GooseDefault::RequestBody`) which when enabled shows up in the `body` field of the `GooseRawMetric`
- add `GooseRawMetric` to the request log, debug log and error log
- fix #332 
This shows up in the Request log (see the second entry which is a POST and therefor has a request body and header):
```json
{"coordinated_omission_elapsed":0,"elapsed":13047,"error":"","final_url":"http://apache/node/84","name":"(Anon) node …
```
=> include the request headers in GooseRequestMetric

CHANGELOG.md, Cargo.toml, README.md, src/lib.rs
- enable [`gzip`](https://docs.rs/reqwest/*/reqwest/struct.ClientBuilder.html#method.gzip) support and set Accept-Encoding header by default in the client; disable with `--no-gzip` or `GooseDefault::NoGzip`
- document how to add custom cookies (https://docs.rs/goose/*/goose/goose/struct.GooseUser.html#custom-cookies)
- update [`rustc_version`](https://docs.rs/rustc_version) dependency to `0.4`
- include client request headers in `GooseRequestMetric` so they show up in the request log and the debug log
- introduce `GooseRawMetric` which contains the `method`, `url`, `headers` and `body` of the client request made, and is now contained in `raw` field of the `GooseRequestMetric` (API change)
- introduce `--request-body` (and `GooseDefault::RequestBody`) which when enabled shows up in the …
=> release 0.13.0

CHANGELOG.md, Cargo.toml, src/goose.rs
- add a test to confirm that a `base_url` can include a path, for example `https://example.com/with/path`
- a relative path will be appended to the above `base_url` including `/with/path/`
- an absolute path will replace `/with/path/`
=> test coverage to confirm base_url can include path

.github/workflows/CI.yml, CHANGELOG.md, src/config.rs
- fix typo where `GooseDefault::RequestBody` was incorrectly referenced as `GooseDefault::RequestsBody`
=> fix a documentation error

CHANGELOG.md, README.md, src/config.rs, src/logger.rs, tests/logs.rs
- introduce `pretty` log format for `--error-format`, `--debug-format`, `--request-format`, and `--task-format`
For example, here's a request log "line" that's pretty formatted:
```
GooseRequestMetric {
elapsed: 2,
raw: GooseRawRequest {
method: Get,
url: "http://apache/",
headers: [],
body: "",
},
name: "(Anon) front page",
final_url: "http://apache/",
redirected: false,
response_time: 124,
status_code: 200,
success: true,
update: false,
user: 0,
error: "",
coordinated_omission_elapsed: 0,
user_cadence: 0,
}
```
=> introduce `pretty` log format

CHANGELOG.md, src/config.rs, src/goose.rs, src/metrics.rs
- general documentation cleanup: fix broken links, fix spelling, etc
=> general documentation cleanups

CHANGELOG.md, src/config.rs
- document GooseConfiguration fields that were only documented as gumpdrop parameters (in order to generate new lines in the help output) so now they're also documented in the code
- prior to this PR some fields were not documented on docs.rs
=> add document comments where help has line feed

CHANGELOG.md, src/metrics.rs, tests/defaults.rs
- fix panic when `--no-task-metrics` is enabled and metrics are printed
- add tests to prevent further regressions
- closes #352 
Recently added logic adding the assumption that the `hosts` vector will always have at least one host. Reworked the logic so this assumption is true and allowing us to print the host whenever possible when printing metrics.
=> fix panic when `--no-task-metrics` is enabled and metrics are printed

examples/simple.rs, examples/simple_closure.rs, examples/simple_with_session.rs, examples/umami/main.rs, src/goose.rs, src/lib.rs, src/manager.rs, src/user.rs, src/worker.rs
I some cases, you want to have a high number of request from a small amount of users which is not possible with second as the time units. This allow you to set a waiting time in Duration.
=> Allow to set duration instead of seconds for task wait configuration

src/goose.rs
Replace path by request name in error message to avoid having a large volume of distinct error for the same endpoint when using path parameters
=> Replace path by request name in error message

CHANGELOG.md, Cargo.toml, src/controller.rs, tests/controller.rs
- updated `tungstenite` dependency to [`0.15`](https://github.com/snapview/tungstenite-rs/blob/master/CHANGELOG.md)
=> update tungstenite version to 0.15

CHANGELOG.md, README.md, examples/drupal_loadtest.rs, examples/simple.rs, examples/simple_closure.rs, examples/simple_with_session.rs, examples/umami/main.rs, src/config.rs, src/goose.rs, src/lib.rs, src/manager.rs, src/metrics.rs, src/util.rs, src/worker.rs, tests/closure.rs, tests/common.rs, tests/controller.rs, tests/defaults.rs, tests/error.rs, tests/logs.rs, tests/no_normal_tasks.rs, tests/one_taskset.rs, tests/redirect.rs, tests/scheduler.rs, tests/sequence.rs, tests/setup_teardown.rs, tests/throttle.rs
In complex use case, a user may need to run some code alongside the GooseAttack which is currently complicated be Goose create a tokio Runtime which prevent user to use #[tokio::main] and run other futures.
This change remove the runtime initialization from Goose and make the function `execute` async.
=> Make GooseAttack.execute async and remove Tokio runtime initialization

CHANGELOG.md, Cargo.toml
- [#361](https://github.com/tag1consulting/goose/pull/361) convert `README.md` (and enhance) into [`The Goose Book`](https://book.goose.rs/)
- [#356](https://github.com/tag1consulting/goose/pull/356) **API change**: make `GooseAttack.execute` async, `main()` function signature changed to:
```rust
#[tokio::main]
fn main() -> Result<(), GooseError> {
```
- [#355](https://github.com/tag1consulting/goose/pull/355) **API change**: add the possibility to attach custom session data `GooseUserData` to each `GooseUser`
- [#355](https://github.com/tag1consulting/goose/pull/355) **API change**: change `GooseTask` signature to take a mutable reference of `GooseUser`:
```rust
async fn example_task_function(user: &mut GooseUser) -> GooseTaskResult {
```
- …
=> release 0.14.0

CHANGELOG.md, src/lib.rs
- [#364](https://github.com/tag1consulting/goose/pull/364) add link from the [Developer Documentation](https://docs.rs/goose) to [The Git Book](https://book.goose.rs)
=> add link from dev docs to the goose book

CHANGELOG.md, Cargo.toml, examples/drupal_memcache.rs, examples/simple.rs, examples/simple_with_session.rs, examples/umami/admin.rs, examples/umami/common.rs, src/docs/goose-book/src/config/rustls.md, src/docs/goose-book/src/controller/telnet.md, src/docs/goose-book/src/getting-started/creating.md, src/goose.rs, src/logger.rs, src/prelude.rs, src/user.rs, tests/no_normal_tasks.rs
- **API change**: introduce `GooseRequest` and `GooseRequestBuilder` for more flexibility when making requests
o remove `GooseUser::post_named`, `GooseUser::head_named`, `GooseUser::delete_named`, `GooseUser::goose_get`, `GooseUser::goose_put`, `GooseUser::goose_head`, `GooseUser::goose_put`, `GooseUser::goose_patch`, `GooseUser::goose_delete`, and `GooseUser::goose_send`
o adds or modifies helpers `GooseUser::get`, `GooseUser::get_named`, `GooseUser::post`, `GooseUser::post_form`, `GooseUser::post_json`, `GooseUser::head`, and `GooseUser::delete`
o replaces `GooseUser::goose_send` with `GooseUser::request` which accepts a `GooseRequest` object
o fixes [#370] (see `GooseRequestBuilder::expect_status_code`)
=> introduce GooseRequest and builder pattern

src/docs/goose-book/src/SUMMARY.md, src/docs/goose-book/src/example/overview.md
- properly link to Example pages after renaming examples
- make it more clear where links go, avoid accidentally steering people aware from the book
=> fix example links

CHANGELOG.md, src/config.rs
- [#385](https://github.com/tag1consulting/goose/pull/385) properly configure `--running-metrics VALUE` when set manually
The configuration logic was reversed, so setting `--running-metrics VALUE` was never working, though using `GooseDefault::RunningMetrics` was (and still is) working.
=> properly configure `--running-metrics VALUE` when set manually

CHANGELOG.md, src/config.rs, src/docs/goose-book/src/getting-started/runtime-options.md, src/docs/goose-book/src/getting-started/tips.md, src/goose.rs, src/util.rs
- [#382](https://github.com/tag1consulting/goose/pull/382) set client timeout to 60 seconds by default, used for all requests made; introduce `--timeout VALUE` where VALUE is seconds as integer or a float; timeout can be configured programatically using `GooseDefault::Timeout`
- introduces `utils::get_float_from_string()`, now used by `utils::get_hatch_rate()`
- updates `set_client_builder()` documentation to reflect how this changes the default Reqwest Client configuration
=> set default request timeout of 60 seconds, configurable

src/config.rs, src/docs/goose-book/src/getting-started/common.md, src/metrics.rs, src/report.rs
Closes #246.
- ~Graph color scheme~
- ~Only display starting/stopping phase when `--no-reset-metrics` is used~
- Investigate spike on transition between starting and started phase
- Confirm that metrics are correct (when throttling is enabled RPS numbers do not match exactly)
- Automated tests
- Add additional graphs.
=> Add requests per second graph to the HTML report.

CHANGELOG.md, src/user.rs, tests/defaults.rs
- [#391](https://github.com/tag1consulting/goose/pull/391) properly sleep for configured `set_wait_time()` walking regularly to exit quickly if the load test ends
- fixes #390 
The sleep loop logic was over-complicated, and a logical error was causing GooseUsers to sleep for an indefinitely long time. Also added a test that will fail if this regresses again.
=> simplify set_wait_time sleep loop; include test

src/metrics.rs, src/report.rs
This is a follow-up of #381 and is part of #246.
=> Add automated tests for requests per second graph in HTML report

CHANGELOG.md, src/goose.rs, src/metrics.rs, src/report.rs, src/util.rs
Closes #246.
- Errors per second
- Average response time per second
- Active users per second
- Active tasks per second
=> Add additional graphs to the HTML report

src/controller.rs
- fix clippy warning
```
% cargo clippy
Compiling goose v0.15.2-dev (.../goose)
warning: field is never read: `client_id`
--> src/controller.rs:223:5
|
223 |     pub client_id: u32,
|     ^^^^^^^^^^^^^^^^^^
|
= note: `#[warn(dead_code)]` on by default
warning: `goose` (lib) generated 1 warning
Finished dev [unoptimized + debuginfo] target(s) in 1.90s
```
=> underscore unread variable

CHANGELOG.md, src/lib.rs
- wake up a couple times a second to handle message and allow for a quick shutdown if the load test is canceled during startup
- fix #401
=> wake regularly during startup

CHANGELOG.md, src/metrics.rs
=> #400: Make sure that graphs are built if the load test is interrupted during startup.

src/lib.rs, src/metrics.rs
=> #405: Move GooseMetrics::record_users_per_second() call to the main loop.

src/lib.rs
~Depends on #411 to avoid conflicts.~
Closes #412.
=> Make sure that the stopping phase is displayed on users graph.

src/report.rs
This should not be a breaking change, since we are not exporting report as public in `lib.rs`:
```
mod report;
```
=> Make structs and functions in report.rs visible only to the crate.

src/docs/goose-book/src/logging/errors.md, src/metrics.rs
Hello, from what I understand, `--error-file` has been renamed to `--error-log`, but that change was missing in the documentation.
=> fix error-log documentation

CHANGELOG.md, src/config.rs, src/graph.rs, src/metrics.rs, src/report.rs
Closes #410.
I used the default color scheme for now. I don't particularly like it, but I didn't have any better idea either.
=> Add granular data to the HTML report graphs

CHANGELOG.md, src/config.rs, src/controller.rs, src/docs/goose-book/src/SUMMARY.md, src/docs/goose-book/src/config/defaults.md, src/docs/goose-book/src/getting-started/runtime-options.md, src/docs/goose-book/src/getting-started/test-plan.md, src/goose.rs, src/lib.rs, src/manager.rs, src/metrics.rs, src/test_plan.rs, src/worker.rs
- introduce `--test-plan` and `GooseDefault::TestPlan` for configuring test plans
- closes https://github.com/tag1consulting/goose/issues/365
- use [`FromStr`] to auto convert `--test-plan "{users},{timespan};{users},{timespan}"`, where `{users}` must be an integer, ie "100", and `{timespan}` can be integer seconds or "30s", "20m", "3h", "1h30m", etc, to internal `Vec<(usize, usize)>` representation
- don't allow `--test-plan` together with `--users`, `--startup-time`, `--hatch-rate` or `--run-time`
- add page to https://book.goose.rs/ explaining how to configure test plans
> The following command tells Goose to start 10 users over 60 seconds and then to run for 5 minutes before shutting down:
> ```bash
> $ cargo run --release -- -H http://local.dev/ --startup-time 1m --users 10 …
```
=> Introduce `--test-plan` for more complex test plans

src/graph.rs, src/lib.rs, src/metrics.rs, src/report.rs
Closes #440. 
- Re-enables report file
- Instead of starting, started, stopping, stopped summary displays a table of plan steps overview
- Removes "Starting" and "Stopping" section from graphs
- Add increasing (green) and decreasing (red) sections to the graph
=> #440: Re-enable HTML report after introduction of test plans.

src/goose.rs
This adds a `error_on_fail()` option to GooseRequest which will return an error if the request fails
=> Add error_on_fail to return error if request fails

CHANGELOG.md, src/controller.rs, src/goose.rs, src/graph.rs, src/lib.rs, src/manager.rs, src/metrics.rs, src/test_plan.rs, tests/closure.rs, tests/controller.rs, tests/defaults.rs, tests/error.rs, tests/one_taskset.rs
- Support multiple and variable speed decrease attack phases
=> Support multiple and variable speed Decrease attack phases

src/docs/goose-book/src/gaggle/config.md
- remove reference to removed option `--only-summary`
- closes #433
=> remove stale reference to --only-summary

CHANGELOG.md, Cargo.toml, examples/drupal_memcache.rs, examples/session.rs, examples/simple.rs, src/docs/goose-book/src/getting-started/creating.md, src/docs/goose-book/src/getting-started/tips.md, src/goose.rs, src/lib.rs
- update version to 0.16.0
- update copyright headers (per https://apache.org/legal/src-headers.html)
- closes https://github.com/tag1consulting/goose/issues/459
=> tag 0.16.0 release

src/docs/goose-book/src/getting-started/tips.md
When I am debugging, I'd like to see where I actually am through a browser by loading the response. It makes things easier. 
The solution is not as pretty as I'd like it to be, but I'd know where I am through the response body. 
I think the script tags are preventing us from opening in a desktop browser (for any length of time)
=> view responses in a browser

CHANGELOG.md, Cargo.toml, src/controller.rs, src/docs/goose-book/src/controller/telnet.md, src/lib.rs, tests/controller.rs
- de-duplicate controller logic to make less fragile (add [`strum`](https://docs.rs/strum) to allow walking of Enum and avoid having to declare all command twice and in the same identical order)
- expose `startup_time` to controllers, resets `hatch_rate` to `None` if previously set
- setting `hatch_rate` resets `startup_time` to `0 if previously set
- test coverage
- closes https://github.com/tag1consulting/goose/issues/425
=> expose `startup_time` to  controllers

src/controller.rs, src/docs/goose-book/src/controller/telnet.md, src/docs/goose-book/src/controller/websocket.md, src/lib.rs, tests/controller.rs
- introduce `ControllerCommandDetails` which includes `help`, `regex`, `process_response` all defined together
- drop `Goose` prefix from Controller
- improve `help` formatting (logically grouping and separating command types)
- move anything that has to be modified when adding new commands to the top of the source file
- closes https://github.com/tag1consulting/goose/issues/470
=> combine controller command logic into central place

CHANGELOG.md, src/config.rs, src/docs/goose-book/src/getting-started/runtime-options.md
- remove example `-h` output, instead pointing to [the book](https://book.goose.rs/getting-started/runtime-options.html)
- includes the following description at the top of the help output: 
```
Goose is a modern, high-performance, distributed HTTP(S) load testing tool,
written in Rust. For more information visit https://book.goose.rs/
The following runtime options are available when launching a Goose load test:
```
- closes https://github.com/tag1consulting/goose/issues/482
- NOTE: this is built on top of another PR which needs to be merged first to properly see the changes in this PR https://github.com/tag1consulting/goose/pull/477
- the full help output now looks as follows:
```
% cargo run --release --example simple -- -h
Compiling goose v0.16.2-dev (~/devel/goose)
Finished release …
```
=> Fix redundant help

CHANGELOG.md, Cargo.toml, src/lib.rs, src/manager.rs, src/metrics.rs, src/util.rs, tests/cancel.rs, tests/throttle.rs
- move CANCELED flag into a global lazy_static so it can be reset and re-used on multiple tests
- move Gaggle-shutdown handling to new SHUTDOWN_GAGGLE flag (also a global lazy_static) so that a Gaggle test shutting down at the same time as a non-Gaggle test is running won't cause both to be shut down
- test coverage with `--run-time` configured
- test coverage without `--run-time` configured (ie, run forever until canceled)
- test coverage with `--iterations` configured
- test coverage with `--test-plan` including canceling while the test is Increasing, Maintaining, and Decreasing
- adds dev-dependency on [`nix`](https://docs.rs/nix) in order to access `kill` for sending `SIGINT`
=> confirm Goose shuts down correctly when canceled

CHANGELOG.md, src/lib.rs, src/metrics.rs, tests/controller.rs
- write report file in the same place that we display final metrics
- don't store open file for duration of load test -- instead, test creation at test-start, then re-open to write report at end of test
- closes https://github.com/tag1consulting/goose/issues/474
- adds test coverage, writing a report file when using the controller
- validate report file is properly created and not-empty
-  cleanup report file at end of successful test
As part of this change, the last thing Goose reports now is where the report file has been written, immediately following the ASCII metrics:
```bash
=== OVERVIEW ===
------------------------------------------------------------------------------
Action       Started               Stopped             Elapsed    Users …
```
=> Don't panic when shutting down with controller and writing report

examples/umami/common.rs
Ran into this error with nids in the thousands. 
```
error: literal out of range for `u8`                                                   
--> examples/umami/common.rs:34:26                                                   
|                                                                                   
34 |                     nid: 34054,                                                   
|                          ^^^^^                                                    
|                                                                                   
= note: the literal `34054` does not fit into the type `u8` whose range is `0..=255`
```
Changed, https://github.com/tag1consulting/goose/blob/d5274ae75d33ab1df20c5d5e0dc995151738ab73/examples/umami/common.rs#L17-L18 from `u8` to …
=> Support nids higher than 255 (u32 vs u8)

src/graph.rs, src/metrics.rs
- fix clippy warnings for unnecessary extra string allocations:
```
= help: consider using `write!` to avoid the extra allocation
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#format_push_string
```
=> avoid unnecessary allocations, clippy cleanups

CHANGELOG.md, src/config.rs, src/docs/goose-book/src/SUMMARY.md, src/docs/goose-book/src/getting-started/custom.md, src/docs/goose-book/src/getting-started/runtime-options.md, src/docs/goose-book/src/getting-started/scenarios.md, src/goose.rs, src/lib.rs, src/test_plan.rs, tests/cancel.rs, tests/closure.rs, tests/common.rs, tests/controller.rs, tests/error.rs, tests/logs.rs, tests/no_normal_tasks.rs, tests/one_taskset.rs, tests/redirect.rs, tests/scenarios.rs, tests/setup_teardown.rs, tests/throttle.rs
- NOTE: depends on #506 being merged fixed (to address clippy errors) -- I've rebased on top of this PR
- assign a unique machine name for each scenario
- introduce `--scenarios` to optionally specify which scenarios run during a load test
- introduce `--scenarios-list` to list scenarios by machine name
- introduce `GooseDefault::Scenarios`
- test coverage
- update `test/common.rs::build_load_test()` to support multiple scenarios (necessary to test this feature)
- add book page titled "Limiting Which Scenarios Run" that provides complete details on this new feature
- closes https://github.com/tag1consulting/goose/issues/479
- closes https://github.com/tag1consulting/goose/issues/472
=> run-time option to configure which scenarios run

CHANGELOG.md, Cargo.toml, src/docs/goose-book/src/controller/telnet.md, src/docs/goose-book/src/getting-started/creating.md, src/docs/goose-book/src/getting-started/metrics.md
- [#498](https://github.com/tag1consulting/goose/issues/498) ignore `GooseDefault::Host` if set to an empty string
- [#487](https://github.com/tag1consulting/goose/pull/487) add dev-dependency on (nix)[https://docs.rs/nix] to provide test coverage confirming proper shutdown from SIGINT (ctrl-c); capture ctrl-c in a lazy_static wrapped in a RwLock so it can be reset
- [#489](https://github.com/tag1consulting/goose/pull/489) don't panic when writing report file and shutting down with controller
- [#505](https://github.com/tag1consulting/goose/pull/505) introduce `--scenarios` (and `GooseDefault::Scenarios`) so a subset of scenarios can be launched, and `--scenarios-list` to display internal machine names for matching
=> release 0.16.3

CHANGELOG.md, src/goose.rs, tests/builder.rs
- use Reqwest's [`method`](https://docs.rs/reqwest/latest/reqwest/struct.Request.html#method.method) function to log proper method, closes #511
- Add test coverage to be confirm that metrics (and therefore logging) are the same whether or not `GooseRequest::builder()` is used
=> log proper method

CHANGELOG.md, src/goose.rs, src/user.rs
Previously, despite what the [documentation](https://docs.rs/goose/0.16.3/goose/goose/index.html#scenario-wait-time) says ("inclusively between the low and high"), the wait time was generated with the upper bound exclusive. This lead to the problem that a constant wait time (the same upper and lower limit) would panic because there is no valid value for rand to return.
`thread 'tokio-runtime-worker' panicked at 'cannot sample empty range', [left out for privacy]\rand-0.8.5\src\rng.rs:134:9`
This PR fixes this by this by using a closed range to generate the wait time. Additionally, a example in the documentation now reflects this usecase.
=> Fix panic when a empty wait time interval is set

CHANGELOG.md, src/logger.rs, tests/logs.rs
To fix #515 I added a macro that properly escapes the values.
I like this approach because it is very lightweight and doesn't add any csv reader functionality as many external dependencies would. On the other hand, this still struggles with nested data and Option<> as well as hard coded headers.
However, currently in order to use the macro in the tests, I use macro_export, but then this leaks into the docs. Does anyone know how to prevent this in Edition 2018? Or is this a case for docs::hidden?
I additionally propose to flatten the GooseRequestMetric.raw into its fields method, url, headers, body for the request log and error log. For GooseDebug, which includes a whole GooseRequestMetric, a similar argument applies.
The Option<> values should further be represented by an empty string …
=> Refactor CSV Logging

src/docs/goose-book/src/getting-started/custom.md
Follow up on #519. As suggested by @jeremyandrews, extending the docs to cover the possibility of using custom command line arguments.
=> Add docs about custom command line args

CHANGELOG.md, Cargo.toml
- release 0.17.0 without gaggle support
- this release updates goose dependencies, most notably tokio (see https://github.com/tag1consulting/goose/pull/529)
- if you require Gaggle support, currently you must use the older 0.16.4 release w/ tokio 1.15 (until https://github.com/tag1consulting/goose/pull/509 lands)
Regression testing:
- https://docs.google.com/spreadsheets/d/1w71FEk-y3zaanHIa5NZnhu8UNVD4lhG3aCjUlANgbhE/edit#gid=0
- https://docs.google.com/document/d/16nTv1rKYNmkyMPFOiL4joCyeh2ETqy9TUrH2c6YjFoc/edit?usp=sharing
=> release 0.17.0 without gaggle support

src/controller.rs, tests/cancel.rs, tests/defaults.rs
- address clippy false-positive with https://rust-lang.github.io/rust-clippy/master/index.html#let_underscore_future (it suggested we had a missing await, but in this case we don't want to await tokio::spawn as we're intentionally starting a new thread but don't need to do anything with the JoinHandle)
- remove unused constants (cut and paste cruft)
=> document why we're not awaiting

CHANGELOG.md, src/goose.rs, src/lib.rs, src/logger.rs, src/metrics.rs, src/user.rs
Fixes #551 by including the following details in the request log:
- `scenario_index`
- `scenario_name`
- `transaction_index` (optional)
- `transaction_name` (optional)
Adding this information to the request log caused the GooseRequestMetric to grow statistically larger than the other members of the GooseMetric enum. Clippy recommended boxing it because of this:
```
% cargo clippy
Checking goose v0.17.1-dev (devel/goose)
warning: large size difference between variants
--> src/metrics.rs:46:1
|
46 | / pub enum GooseMetric {
47 | |     Request(GooseRequestMetric),
| |     --------------------------- the largest variant contains at least 280 bytes
48 | |     Transaction(TransactionMetric),
| |     ------------------------------ the second-largest variant contains at least 72 bytes
49 | | …
```
=> log scenario index and name, and transaction index and name

CHANGELOG.md, Cargo.toml
- remove serde_cbor no longer required due to [#529]
- fixes https://github.com/tag1consulting/goose/issues/540
=> remove dependency on serde_cbor

CHANGELOG.md, src/graph.rs
- don't build legend if there's no data to display
- fixes https://github.com/tag1consulting/goose/issues/545 and https://github.com/tag1consulting/goose/issues/533
=> don't panic when graph has no data

src/goose.rs, src/lib.rs
When running goose tests with large amounts of goose users on my machine, it takes roughly 1 minute to initialize 1000 goose users. It appears that building each reqwest client for each goose user is an expensive operation. If we change the behavior to build only 1 reqwest client, and clone the object when creating the goose users, we can significantly increase initialization performance. With this change, I can create a few million goose users and only takes a couple of seconds to complete the initialization phase on my machine.
=> Speed up user initialization

src/metrics.rs
- Fixes clippy detected issue:
```
error: this `if` branch is empty
Error:     --> src/metrics.rs:2549:9
|
2549 |         if self.hosts.len() == 1 {}
|         ^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: you can remove it: `self.hosts.len() == 1;`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_if
= note: `-D clippy::needless-if` implied by `-D warnings`
```
- Using `git blame` confirmed this was added during [#342](https://github.com/tag1consulting/goose/pull/342)
- This slipped in during that earlier PR, and is not necessary; simply removing
=> remove empty if branch

CHANGELOG.md, Cargo.toml
- fixes https://github.com/tag1consulting/goose/issues/558 
- only enable required features from `chrono`, addressing https://rustsec.org/advisories/RUSTSEC-2020-0071
> A possible workaround for crates affected through the transitive dependency in chrono, is to avoid using the default oldtime feature dependency of the chrono crate by disabling its default-features and manually specifying the required features instead.
- source of the fix: https://github.com/chronotope/chrono/issues/602#issuecomment-1242149249
This fixes the following issue detailed [at the link above](https://rustsec.org/advisories/RUSTSEC-2020-0071):
> Unix-like operating systems may segfault due to dereferencing a dangling pointer in specific circumstances. This requires an environment variable to be set in a different …
=> disable default chrono features, fix potential segfault in the time crate

CHANGELOG.md, Cargo.toml, src/docs/goose-book/src/controller/telnet.md, src/docs/goose-book/src/getting-started/creating.md, src/docs/goose-book/src/getting-started/metrics.md, src/docs/goose-book/src/getting-started/scenarios.md
- [#557](https://github.com/tag1consulting/goose/pull/557) speed up user initialization on Linux
- [#559](https://github.com/tag1consulting/goose/pull/559) disable unnecessary features in chronos, avoid potential segfault in time crate: https://rustsec.org/advisories/RUSTSEC-2020-0071
=> v0.17.2 release

src/config.rs, src/goose.rs
Adding the possibility to setup Reqwest client with ignore certificate mode.
This feature is used in cases https is used for non terminated proxies, but when testing internal infrastructure setups eg. when self signed or dev certificates are being used.
This is what I currently need to be able to use goose in the setup I have to load test.
=> allow to skip cert validation for internal test situations

CHANGELOG.md, src/docs/goose-book/src/getting-started/runtime-options.md
- update documentation for https://github.com/tag1consulting/goose/pull/565, `--accept-invalid-certs`
=> document --accept-invalid-certs

src/graph.rs
- fix clippy error: https://rust-lang.github.io/rust-clippy/master/index.html#/incorrect_partial_ord_impl_on_ord_type
=> fix non_canonical_partial_ord_impl to ensure PartialOrd and Ord agree

CHANGELOG.md, src/util.rs
- implement non-utf8-specific truncation
- add tests to confirm truncate_string() works with Japanese, Chinese, and Korean characters
- fixes https://github.com/tag1consulting/goose/issues/567
=> don't panic when truncating non-utf8

CHANGELOG.md, src/lib.rs, tests/session.rs
- validate that with multiple users, each user has a unique and maintained session
- validate that with multiple users, each user has their own cookie jar
- the optimization (https://github.com/tag1consulting/goose/pull/557/files#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759R775) in #557 caused the problem reported in #571, specifically because by cloning the reqwest client we're also cloning the cookie jar, which means all GooseUsers end up storing cookies in the same jar. Unfortunately it's not possible to clone the client and then change the cookie jar as this is only exposed when building the client.
- fixes https://github.com/tag1consulting/goose/issues/571
=> test that per-user sessions are working

src/graph.rs
Solves this issue: https://github.com/tag1consulting/goose/issues/429
This PR creates a new struct `ItemsPerSecond` and some accompanying methods that encapsulate the logic of the underlying hash map.
**Note:**
I had to use `#[allow(dead_code)]` because for some reason the compiler would complain about dead code, even though the code is being used.
=> Issue 429: Implement ItemsPerSecond

src/goose.rs
This PR addressed issue https://github.com/tag1consulting/goose/issues/531.
The original bug report provided a minimum reproducible code, but I think we're able to shrink that even further to:
```rust
async fn test_case(user: &mut GooseUser) -> TransactionResult {
let goose = user
.get("my/url")
.await?;
let _ = goose.response?;
Ok(())
}
```
Trying to compile a loadtest with this code should give the following error:
```
the trait `From<reqwest::error::Error>` is not implemented for `Box<TransactionError>`
```
With this PR, it should compile cleanly.
=> Issue #531: Fix missing impl for TransactionError

src/report.rs
fixes the report bottom erros, since they can be from OS current lang
=> update: add utf-8 meta charset tag to html report

src/graph.rs
https://github.com/tag1consulting/goose/issues/526
This is a relatively simple change that prevents the chart from rendering 0 values.
The base change is in `TimeSeriesValue`, where `get_graph_value` is converted to detect zeros, if it does, it returns a `None`. Converting the return value from `U` to `Option<U>` then allows us to filter out blank values when constructing chart data in `add_timestamp_to_html_graph_data`.
To test this, just run a few different transactions, and maybe add `set_wait_time` to make sure you have some seconds where nothing happened. Then open up the HTML report and looks at the pretty chart.
It's worth noting that the person who opened the original issue complained that this solution actually makes graphs looks worse, which might very well be true in some …
=> Issue 526: Fix blank graph bits

README.md
- rework README to try and make it more concise and scannable
=> Make more concise and scannable

tests/one_taskset.rs
Ignore gaggle tests consistently to ensure they don't run, even with `--all-features` enabled:
```
+#[ignore]
#[tokio::test(flavor = "multi_thread", worker_threads = 8)]
-#[cfg_attr(not(feature = "gaggle"), ignore)]
#[serial]
```
=> ignore gaggle tests consistently

CHANGELOG.md, Cargo.toml, examples/drupal_memcache.rs, examples/umami/admin.rs, examples/umami/common.rs, examples/umami/english.rs, examples/umami/spanish.rs, src/controller.rs, src/goose.rs, src/lib.rs, src/report/markdown.rs, src/user.rs, src/util.rs, tests/common.rs, tests/controller.rs
This PR updates several key dependencies to their latest versions and addresses Clippy warnings to improve code quality.
- Updated rustls to 0.23
- Updated tungsteniteto 0.26
- Updated serial_test to 3.2
- Updated httpmock to 0.7
- Updated rand to 0.9
- Updated itertools to 0.14
- Updated strum to 0.27
- Updated nix to 0.29
- Updated downcast-rs to 2.0
Fixes https://github.com/tag1consulting/goose/issues/591
=> Update Dependencies and Fix Clippy Warnings

CHANGELOG.md, Cargo.toml, examples/umami/common.rs, src/controller.rs, src/graph.rs, src/metrics/common.rs, tests/builder.rs, tests/cancel.rs, tests/closure.rs, tests/common.rs, tests/controller.rs, tests/defaults.rs, tests/error.rs, tests/logs.rs, tests/no_normal_tasks.rs, tests/one_taskset.rs, tests/scenarios.rs, tests/scheduler.rs, tests/sequence.rs, tests/session.rs, tests/setup_teardown.rs, tests/throttle.rs
This PR fixes all clippy warnings that appear with the latest Rust version. These warnings are related to the new `mismatched-lifetime-syntaxes` lint that was introduced in recent Rust versions.
- Updated function signatures to use explicit lifetime annotations where needed
- Changed `Vec<Mock>` to `Vec<Mock<'_>>` in test files for consistent lifetime syntax
- Changed `Vec<Node>` to `Vec<Node<'_>>` in the umami example
- All changes maintain backward compatibility and functionality
- Updated version (as we're working toward a new release)
- 16 test files in `tests/` directory
- 1 example file in `examples/umami/common.rs`
- Various other files with minor clippy fixes
- All clippy warnings have been resolved
- `cargo clippy --all-targets --all-features -- -D warnings` now passes without …
=> Fix clippy warnings for latest Rust version

examples/graphql_loadtest.rs, src/config.rs, src/docs/goose-book/src/SUMMARY.md, src/docs/goose-book/src/example/graphql.md, src/goose.rs
This PR adds lightweight GraphQL support to Goose through dedicated helper methods that build on the existing HTTP/JSON infrastructure.
**New GraphQL Helper Methods:**
-  - Send GraphQL queries to specified endpoint
-  - Send named GraphQL queries for better metrics tracking
**Documentation & Examples:**
- Complete GraphQL documentation with realistic sample output
- Working GraphQL load test example ()
- Integration with existing Goose book documentation
- **Zero additional dependencies** - Built on existing HTTP/JSON infrastructure
- **Full Goose integration** - Works with all existing metrics, logging, and reporting
- **Easy to use** - Simple helper methods for GraphQL queries and mutations
- **Named requests** - Better metrics tracking with custom operation names
- **Variable …
=> Add GraphQL support with helper methods and documentation

src/docs/goose-book/src/SUMMARY.md, src/docs/goose-book/src/config/proxy.md
This PR adds comprehensive documentation for configuring SOCKS proxies with Goose load tests.
- New documentation page: `src/docs/goose-book/src/config/proxy.md`
- Updated table of contents in `src/docs/goose-book/src/SUMMARY.md`
- SOCKS5 proxy setup with required `reqwest` features
- Environment variable configuration (`socks5h://` for DNS through proxy)
- HTTP/HTTPS proxy support with authentication
- Real-world use cases (Burp Suite, SSH tunnels, corporate proxies)
- Complete working example with dependencies
- Troubleshooting common issues
Code examples have been verified to compile and work correctly with the documented dependency configuration.
Closes https://github.com/tag1consulting/goose/issues/490
=> Add SOCKS proxy configuration documentation
